= Jenkins 构建 deb 包
notfound <notfound@notfound.cn>
1.0, 2024-07-08: init

:page-slug: deb-jenkins
:page-category: deb
:page-tags: deb,jenkins,linux
:page-draft: false

Jenkins 构建 deb 包。

系统环境：Debian 12。

== 概览

Jenkins 构建 deb 大致流程，只涉及需要配置的服务或者程序：

.Jenkins 构建 deb 概览
[source,plantuml]
----
@startuml
box "jenkins.notfound.cn\n(构建 deb 包)" #LightBlue
    participant jenkins
    participant sbuild
    participant apt
    participant dput
    participant curl
end box

box "packages.notfound.cn\n(apt 管理 deb 包)" #LightGreen
    participant "WebDAV\n(nginx)" as dav
    participant "CGI\n(nginx)" as cgi
    participant reprepro
end box

box "proxy.notfound.cn\n(apt 缓存 deb)"
    participant "squid-deb-proxy" as proxy
end box

activate jenkins

jenkins  -> sbuild : 打包 deb
activate sbuild
sbuild   -> apt    : 下载依赖
activate apt
apt      -> proxy  : 使用缓存加速依赖下载
activate proxy
apt     <-- proxy
deactivate proxy
sbuild  <-- apt
deactivate apt
jenkins <-- sbuild
deactivate sbuild

jenkins  -> dput   : 上传 deb
activate dput
dput     -> dav    : http(s) 协议上传
activate dav
dput    <-- dav
deactivate dav
jenkins <-- dput
deactivate dput

jenkins  -> curl        : 添加 deb 到 apt 源
activate curl
curl     -> cgi         : CGI 执行 shell
activate cgi
cgi      -> reprepro    : 添加 apt 数据
activate reprepro
cgi     <-- reprepro
deactivate reprepro
curl    <-- cgi
deactivate cgi
jenkins <-- curl
deactivate curl

deactivate jenkins
@enduml
----

== APT 缓存

参考 link:/posts/deb-squid-deb-proxy/[squid-deb-proxy 缓存 apt 数据]。

== APT 包管理

参考 link:/posts/deb-reprepro/[使用 reprepro 制作 apt 源]。

== Jenkins

参考 link:/posts/jenkins-install/[搭建 Jenkins]。

=== Jenkis 节点

* 如果需要虚拟机，参考 link:/posts/qemu-install/[Linux 安装 QEMU-KVM]；
* 参考 link:/posts/jenkins-node/[添加 Jenkins 节点]。

==== 配置节点

1. 安装基础工具：
+
[source,bash]
----
sudo apt install curl expect gnupg
----
* `expect` 处理命令交互脚本。
+
2. 配置 sbuild 环境，参考：link:/posts/deb-sbuild/[sbuild 构建 deb 包]
+
3. 配置 dput，参考：link:/posts/deb-reprepro/#_dput[dput 章节]

=== Jenkins 相关脚本

==== tarball

生成 .tar.gz 包，文件名称从 `debian/changelog` 获取：

..jenkins/tarball.sh
[source,bash]
----
#!/bin/bash -e

name=$(dpkg-parsechangelog --show-field Source)
# The version number of a package. The format is: [epoch:]upstream_version[-debian_revision]
version=$(dpkg-parsechangelog --show-field Version | sed -E 's/^([0-9]+:)?([^:-]+)(-.*)?$/\2/')

git archive --format=tar.gz --prefix="${name}_${version}/" HEAD > "../${name}_${version}.orig.tar.gz"

# vim: set tabstop=4 shiftwidth=4 expandtab
----

==== sbuild

构建 debina packages：

..jenkins/sbuild.sh
[source,bash]
----
#!/bin/bash -e

architecture=$1
distribution=$2

case "$architecture" in
    arm64|amd64)
        ;;
    *)
        echo "invalid architecture: $architecture"
        ;;
esac

case "$distribution" in
    bookworm|bullseye)
        ;;
    jammy|focal)
        ;;
    *)
        echo "invalid distribution: $distribution"
        ;;
esac

sbuild \
    --arch="$architecture" \
    --dist="$distribution" \
    --append-to-version="+$distribution"

# vim: set tabstop=4 shiftwidth=4 expandtab
----

添加额外的 apt 源需要修改该文件，如，添加 nodejs 源：

[source,bash]
----
sbuild \
    --dist=bookworm \
    --extra-repository="deb http://deb.nodesource.com/node_20.x nodistro main" \
    --extra-repository-key="./.jenkins/nodesource.asc"
----
* `extra-repository-key` 需要将 GPG 公钥下载到本地后通过文件路径添加。

Ubuntu amd64/i386 源位于 http://archive.ubuntu.com/[archive]，其他如 arm64/riscv64 源位于 http://ports.ubuntu.com/[ports]，在使用镜像加速时源路径不同，如：

[source,bash]
----
# amd64
sbuild \
    --dist=jammy \
    --extra-repository="deb http://mirrors.cloud.tencent.com/ubuntu/ jammy universe" \
    --extra-repository="deb http://mirrors.cloud.tencent.com/ubuntu/ jammy-updates universe"

# arm64
sbuild \
    --dist=jammy \
    --extra-repository="deb http://mirrors.cloud.tencent.com/ubuntu-ports/ jammy universe" \
    --extra-repository="deb http://mirrors.cloud.tencent.com/ubuntu-ports/ jammy-updates universe"
----

==== dput

上传 deb 相关数据：

..jenkins/dput.exp
[source,bash]
----
#!/usr/bin/expect -f

# dput.exp [password] [host] <package(s).changes>
set password    [lindex $argv 0]
set host        [lindex $argv 1]
set changes     [lrange $argv 2 end]

set timeout 300

foreach change $changes {
    spawn dput -f $host $change

    expect {
        "Password for *:" {
            send "$password\r"
        }
        timeout {
            puts "error: timeout"
            exit 1
        }
    }
}

expect eof

# vim: set tabstop=4 shiftwidth=4 expandtab
----

==== Jenkins

jenkins 构建流程：

..jenkins/Jenkinsfile
[source,groovy]
----
pipeline {
    agent {
        label 'sbuild-all'
    }

    environment {
        PACKAGES_URL = 'http://packages.notfound.cn'
        DPUT_CREDS = credentials('dput-jenkins')
    }

    stages {
        stage('Cleanup') {
            steps {
                cleanWs(patterns: [[pattern: 'source', type: 'EXCLUDE']])
            }
        }

        stage('Source') {
            steps {
                dir('source') {
                    git branch: 'main', url: 'https://example.com/notfound/hello.git'
                    sh './.jenkins/tarball.sh'
                }
            }
        }

        stage('Build') {
            steps {
                dir('source') {
                    sh './.jenkins/sbuild.sh amd64 bookworm'
                    sh './.jenkins/sbuild.sh amd64 jammy'
                    sh './.jenkins/sbuild.sh arm64 bookworm'
                    sh './.jenkins/sbuild.sh arm64 jammy'
                }
            }
        }

        stage('Upload') {
            steps {
                dir('source') {
                    sh './.jenkins/dput.exp ${DPUT_CREDS_PSW} bookworm ../*bookworm*.changes'
                    sh 'curl --user ${DPUT_CREDS_USR}:${DPUT_CREDS_PSW} -X POST --fail-with-body -sL ${PACKAGES_URL}/incoming/debian/bookworm/cgi-bin/reprepro.cgi'

                    sh './.jenkins/dput.exp ${DPUT_CREDS_PSW} jammy ../*jammy*.changes'
                    sh 'curl --user ${DPUT_CREDS_USR}:${DPUT_CREDS_PSW} -X POST --fail-with-body -sL ${PACKAGES_URL}/incoming/ubuntu/jammy/cgi-bin/reprepro.cgi'
                }
            }
        }
    }
}
----
