= Go etcd/raft 基本使用
notfound <notfound@notfound.cn>
1.0, 2023-03-25: init

:page-slug: distribution-etcd-raft
:page-category: distribution
:page-tags: etcd

Etcd 提供了一个 raft 包 https://pkg.go.dev/go.etcd.io/etcd/raft/v3#Ready[etcd/raft]，用户需要自己实现网络部分传输消息和存储部分来保存 raft 日志和状态。

官方提供了一个示例 https://github.com/etcd-io/etcd/tree/v3.5.7/contrib/raftexample[raftexample]，基于该示例进行说明。

== 概览

kvstore 和 raft 节点关系：

[source,plantuml]
----
@startuml
(kvstore) --> (raftnode) : node.Propse()
(kvstore) <-- (raftnode) : committedEntries
@enduml
----
1. kvstore 通过 `node.Propose()` 将值或者通过 `node.ProposeConfChange()` 将配置发送到 raft 状态机；
2. kvstore 从 raft 状态机读取已提交的条目 committedEntries 或者快照。

raft 节点之间的关系：

[source,plantuml]
----
@startuml
(raftnode1) --> (raftnode2) : transport.Send()
(raftnode2) --> (raftnode2) : node.Step()
(raftnode1) --> (raftnode3) : transport.Send()
(raftnode3) --> (raftnode3) : node.Step()
@enduml
----
1. 主节点将 Messages （心跳、配置、普通数据等）发送到其他节点；
2. 从节点收到消息后通过 `node.Step()` 推动本地状态机。

== 启动

=== 预写日志和快照

启动时需要读取预写日志和快照。

1. 从预写日志中获取所有快照信息 `[]walpb.Snapshot`：
+
.walpb.Snapshot
[source,go]
----
type Snapshot struct {
	Index uint64
	Term  uint64
	ConfState            *raftpb.ConfState
}
----
+
2. 根据预写日志 `[]walpb.Snapshot` 加载可用且最新的快照 `raftpb.Snapshot`：
+
.raftpb.Snapshot
[source,go]
----
type Snapshot struct {
	Data     []byte
	Metadata SnapshotMetadata
}
----
+
3. 从快照中元数据 `snapshot.Metadata` 获取 `walpb.Snapshot` 中的 `Index` 和 `Term`；
+
.raftpb.SnapshotMetadata
[source,go]
----
type SnapshotMetadata struct {
	ConfState ConfState 
	Index     uint64
	Term      uint64
}
----
+
4. 根据 `walpb.Snapshot` 打开预写日志；
5. 从预写日志中读取 `raftpb.HardState` 和 `[]raftpb.Entry`；
6. 将 `raftpb.Snapshot`、`raftpb.HardState` 和 `[]raftpb.Entry` 应用到 `raft.MemoryStorage`。

=== Raft 节点以及网络传输

1. 通过 `raft.StartNode()` 或者 `raft.RestartNode()` 启动节点
2. 通过 `rafthttp.Transport{}` 进行网络连接：
a. 添加 raft 节点客户端，用来和其他 raft 节点建立连接；
b. 在独立协程上启动 HTTP 服务，准备接收 raft 相关请求，接收到数据后需要调用 `node.Step` 推动 raft 状态机运行。

数据传输时会将快照和其他数据分开，避免因处理快照阻塞时间过长而影响到心跳。

== Ready

`Ready` 是一个核心的结构，大部分操作都和 `Ready` 相关。

[source,go]
----
type Ready struct {
	// The current volatile state of a Node.
	// SoftState will be nil if there is no update.
	// It is not required to consume or store SoftState.
	*SoftState // <1>

	// The current state of a Node to be saved to stable storage BEFORE
	// Messages are sent.
	// HardState will be equal to empty state if there is no update.
	pb.HardState // <2>

	// ReadStates can be used for node to serve linearizable read requests locally
	// when its applied index is greater than the index in ReadState.
	// Note that the readState will be returned when raft receives msgReadIndex.
	// The returned is only valid for the request that requested to read.
	ReadStates []ReadState // <3>

	// Entries specifies entries to be saved to stable storage BEFORE
	// Messages are sent.
	Entries []pb.Entry // <4>

	// Snapshot specifies the snapshot to be saved to stable storage.
	Snapshot pb.Snapshot // <5>

	// CommittedEntries specifies entries to be committed to a
	// store/state-machine. These have previously been committed to stable
	// store.
	CommittedEntries []pb.Entry // <6>

	// Messages specifies outbound messages to be sent AFTER Entries are
	// committed to stable storage.
	// If it contains a MsgSnap message, the application MUST report back to raft
	// when the snapshot has been received or has failed by calling ReportSnapshot.
	Messages []pb.Message // <7>

	// MustSync indicates whether the HardState and Entries must be synchronously
	// written to disk or if an asynchronous write is permissible.
	MustSync bool
c
----
<1> 包含 leader id 和节点状态，易失，无需保存；
<2> 包含任期、任期内的投票以及 commit index，需要在发送 Messages 前保存到 storage；
<3> 当应用的索引大于 ReadState 中的索引时，可用于线性读；
<4> 需要在发送 Messages 前保存到 storage；
<5> 快照，需要保存到 storage；
<6> 已被提交到状态机的条目；
<7> 在 Entries 被保存到 storage 后，需要将 Messages 发送出去。

=== Ready 处理

1. 持久化 `ready.Snapshot` (类型 `raftpb.Snapshot`)：
+
a. 持久化快照本身 `raftpb.Snapshot`；
+
b. 持久化快照相关的预写日志 `walpb.Snapshot`(内容根据从 `snap.Metadata` 获取);
+
这使得快照文件可能单独存在，但可以防止预写日志条目没有对应的快照文件（启动时先读预写日志后读快照，再根据快照读预写）。
+
2. 持久化预写日志包括 `ready.HardState` 和 `ready.Entries`：
+
.raftpb.HardState
[source,go]
----
type HardState struct {
	Term   uint64
	Vote   uint64
	Commit uint64
}
----
+
.raftpb.Entry
[source,go]
----
type Entry struct {
	Term  uint64
	Index uint64
	Type  EntryType
	Data  []byte
}
----
+
3. 将快照 `ready.Snapshot` 应用到 `raft.MemoryStorage`；
4. 将快照 `ready.Snapshot` 发布 (使用 channel 通知 kvstore 从快照恢复数据)；
5. 将 `ready.Entries` 追加到 `raft.MemoryStorage`；
6. 发送 `ready.Messages` 到其他节点, 可根据 MessageType 将快照和其他类型数据用不同的方式发送到 `To` 指定的目标：
+
.raftpb.Message
[source,go]
----
type Message struct {
	Type MessageType
	To   uint64
	From uint64
	Term uint64
	LogTerm uint64
	Index   uint64
	Entries []Entry
	Commit  uint64
	Snapshot   *Snapshot
	Reject     bool
	RejectHint uint64
	Context    []byte
}
----
+
.raftpb.MessageType 
[source,go]
----
type MessageType int32

const (
	MsgHup            MessageType = 0
	MsgBeat           MessageType = 1
	MsgProp           MessageType = 2
	MsgApp            MessageType = 3
	MsgAppResp        MessageType = 4
	MsgVote           MessageType = 5
	MsgVoteResp       MessageType = 6
	MsgSnap           MessageType = 7
	MsgHeartbeat      MessageType = 8
	MsgHeartbeatResp  MessageType = 9
	MsgUnreachable    MessageType = 10
	MsgSnapStatus     MessageType = 11
	MsgCheckQuorum    MessageType = 12
	MsgTransferLeader MessageType = 13
	MsgTimeoutNow     MessageType = 14
	MsgReadIndex      MessageType = 15
	MsgReadIndexResp  MessageType = 16
	MsgPreVote        MessageType = 17
	MsgPreVoteResp    MessageType = 18
)
----
+
*  如果消息类型为 `MsgSnap` 则需要在消息发送完成后调用 `Node.ReportSnapshot()`
+
7. 将已提交的条目 `ready.CommittedEntries`(类型 `raftpb.Entry`)发布 ，需要根据类型进行处理：
+
.raftpb.EntryType
[source,go]
----
type EntryType int32

const (
	EntryNormal       EntryType = 0
	EntryConfChange   EntryType = 1
	EntryConfChangeV2 EntryType = 2
)
----
+
* `EntryNormal` 普通日志条目，通过 channel 发送给 kvstore；
* `EntryConfChange` 配置变更，通过 `raft.ApplyConfChange()` 应用变更，再根据配置变更类型增加、更新、或删除节点：
+
.raftpb.ConfChangeType
[source,go]
----
type ConfChangeType int32

const (
	ConfChangeAddNode        ConfChangeType = 0
	ConfChangeRemoveNode     ConfChangeType = 1
	ConfChangeUpdateNode     ConfChangeType = 2
	ConfChangeAddLearnerNode ConfChangeType = 3
)
----
+
8. 调用 `node.Advance()`，节点可调用下一个 `node.Read()`

== Propose

提案包括两种：

* 普通提案 `node.Propose()`
* 配置变更提案 `node.ProposeConfChange()`
