= AsciiDoc Template
notfound <notfound@notfound.cn>
1.0, 2022-06-11: init

:page-slug: gatsby-asciidoc-template
:page-category: blog
:page-draft: true

== Verbatim and Source Blocks

=== Source Code Blocks

[source,ruby]
----
require 'sinatra'

get '/hi' do
  "Hello World!"
end
----

[,ruby]
----
require 'sinatra'

get '/hi' do
  "Hello World!"
end
----

=== Callouts

[source,ruby]
----
require 'sinatra' <1>

get '/hi' do <2> <3>
  "Hello World!"
end
----
<1> Library import
<2> URL mapping
<3> Response block

----
line of code // <1>
line of code # <2>
line of code ;; <3>
line of code <!--4-->
----
<1> A callout behind a line comment for C-style languages.
<2> A callout behind a line comment for Ruby, Python, Perl, etc.
<3> A callout behind a line comment for Clojure.
<4> A callout behind a line comment for XML or SGML languages like HTML.

=== PlantUML

[source,plantuml]
----
@startuml
Bob -> Alice : hello
@enduml
----

== Admonitions

NOTE: NOTE

[TIP]
It's possible to use Unicode glyphs as admonition icons.

[IMPORTANT]
.Feeding the Werewolves
====
While werewolves are hardy community members, keep in mind the following dietary concerns:

. They are allergic to cinnamon.
. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.
====

CAUTION: CAUTION

WARNING: Wolpertingers are known to nest in server racks.
Enter at your own risk.
