= Git 服务端 Hooks
notfound <notfound@notfound.cn>
1.0, 2020-06-20: 创建
:sectanchors:

:page-slug: git-server-hooks
:page-category: git

== 准备

=== 概览

推送两个分支过程：

[source,plantuml]
----
@startuml
participant "git server" as git
participant "pre-receive" as pre_receive
participant update
participant "post-receive" as post_receive

activate git
  git --> pre_receive : stdin\noldrev newrev refname\noldrev newrev refname
    activate pre_receive
    git <-- pre_receive
    deactivate pre_receive
  git --> update : cmd args\nrefname oldrev newrev
    activate update
    git <-- update
    deactivate update
  git --> update : cmd args\nrefname oldrev newrev
    activate update
    git <-- update
    deactivate update
  git --> post_receive : stdin\noldrev newrev refname\noldrev newrev refname
    activate post_receive
    git <-- post_receive
    deactivate post_receive
deactivate git
@enduml
----
* pre-receive、post-receive 从标准输入读取数据
* update 从命令行参数读取数据

=== 测试仓库

[source,bash]
----
git init --bare git-server-hook.git # <1>
git clone git-server-hook.git # <2>
----
<1> 初始化一个裸仓库，服务端使用该方式保存数据
<2> 直接本地拉取代码，之后用户推送测试

== Git 钩子

=== pre-receive

特点：

* 无参数调用
* 标准输入传递引用信息
* 以非零值退出，所有的推送内容都不会被接受

用途：

* 钩子阻止对引用进行非快进（non-fast-forward）的更新
* 对该推送所修改的所有引用和文件进行访问控制

示例：

在裸仓库新建文件 `hooks/pre-receive` ，并为该文件添加可执行权限：

.hooks/pre-receive
[source,bash]
----
#!/bin/sh

echo "------------"
env | grep "GIT_" # <1>
echo "------------"

# sha1-old SP sha1-new SP refname LF <2>
while read oldrev newrev refname
do
    printf "%-40s %-40s %s\n"  $oldrev $newrev $refname
done
echo "------------"

exit 1 # <3>
----
<1> 钩子在执行时，会传入一些 GIT 相关环境变量
<2> 从标准输入读取推送引用信息，格式为： `sha1-old SP sha1-new SP refname LF`，推送多个引用（分支、标签）会有多行。
<3> 模拟失败情况，会阻止所有引用更新

测试推送两个分支：

[source,text]
----
$ git push origin main:main main:master
枚举对象中: 3, 完成.
对象计数中: 100% (3/3), 完成.
写入对象中: 100% (3/3), 199 字节 | 199.00 KiB/s, 完成.
总共 3（差异 0），复用 0（差异 0），包复用 0
remote: ------------
remote: GIT_ALTERNATE_OBJECT_DIRECTORIES=/tmp/git/git-server-hook.git/./objects
remote: GIT_QUARANTINE_PATH=/tmp/git/git-server-hook.git/./objects/incoming-behIHS
remote: GIT_EXEC_PATH=/usr/lib/git-core
remote: GIT_DIR=.
remote: GIT_PUSH_OPTION_COUNT=0
remote: GIT_OBJECT_DIRECTORY=/tmp/git/git-server-hook.git/./objects/incoming-behIHS
remote: ------------
remote: 0000000000000000000000000000000000000000 b1f48e4fa15d08018b08052af4c0063d689a12cf refs/heads/main
remote: 0000000000000000000000000000000000000000 b1f48e4fa15d08018b08052af4c0063d689a12cf refs/heads/master
remote: ------------
To /tmp/git/git-server-hook.git
 ! [remote rejected] main -> main (pre-receive hook declined)
 ! [remote rejected] main -> master (pre-receive hook declined)
error: 推送一些引用到 '/tmp/git/git-server-hook.git' 失败
----

=== update

特点：

* 接受三个参数：引用名（分支、标签完整名称），推送前的引用 SHA-1 值，以及用户准备推送的 SHA-1 值
* 会为每一个准备更新的引用各运行一次
* 如果 update 脚本以非零值退出，只有相应的那一个引用会被拒绝，其余的依然会被更新

用途：

* 钩子阻止对引用进行非快进（non-fast-forward）的更新
* 对该推送所修改的所有引用和文件进行访问控制

示例：

在裸仓库新建文件 `hooks/update` ，并为该文件添加可执行权限：

.hooks/update
[source,bash]
----
#!/bin/sh

<1>
refname="$1"
oldrev="$2"
newrev="$3"

echo "----------"
printf "%s %s %s\n" $refname $oldrev $newrev

exit 1 # <2>
----
<1> 读取程序三个参数
<2> 模拟失败情况，会阻止当前引用更新

推送两个分支：

[source,text]
----
$ git push origin main:main main:master
枚举对象中: 3, 完成.
对象计数中: 100% (3/3), 完成.
写入对象中: 100% (3/3), 199 字节 | 199.00 KiB/s, 完成.
总共 3（差异 0），复用 0（差异 0），包复用 0
remote: ----------
remote: refs/heads/main 0000000000000000000000000000000000000000 b1f48e4fa15d08018b08052af4c0063d689a12cf
remote: error: hook declined to update refs/heads/main
remote: ----------
remote: refs/heads/master 0000000000000000000000000000000000000000 b1f48e4fa15d08018b08052af4c0063d689a12cf
remote: error: hook declined to update refs/heads/master
To /tmp/git/git-server-hook.git
 ! [remote rejected] main -> main (hook declined)
 ! [remote rejected] main -> master (hook declined)
error: 推送一些引用到 '/tmp/git/git-server-hook.git' 失败
----

=== post-receive

特点：

* 无参数调用
* 标准输入传递引用信息
* 在整个过程完结以后运行
* 无法终止推送进程
* 客户端在它结束运行之前将保持连接状态

用途：

* 更新其他系统服务或者通知用户，如：向 CI 发送构建请求

示例：

在裸仓库新建文件 `hooks/post-receive` ，并为该文件添加可执行权限：

.hooks/post-receive
[source,bash]
----
#/bin/sh

echo "------------"

# sha1-old SP sha1-new SP refname LF <1>
while read oldrev newrev refname
do
    printf "%-40s %-40s %s\n"  $oldrev $newrev $refname
done

exit 1 # <2>
----
<1> 从标准输入读取推送引用信息，格式为： `sha1-old SP sha1-new SP refname LF`，推送多个引用（分支、标签）会有多行。同 `pre-receive` 格式
<2> 失败不会对推送产生影响

推送两个分支：

[source,text]
----
$ git push origin main:main main:master
枚举对象中: 3, 完成.
对象计数中: 100% (3/3), 完成.
写入对象中: 100% (3/3), 199 字节 | 199.00 KiB/s, 完成.
总共 3（差异 0），复用 0（差异 0），包复用 0
remote: ------------
remote: 0000000000000000000000000000000000000000 b1f48e4fa15d08018b08052af4c0063d689a12cf refs/heads/main
remote: 0000000000000000000000000000000000000000 b1f48e4fa15d08018b08052af4c0063d689a12cf refs/heads/master
To /tmp/git/git-server-hook.git
 * [new branch]      main -> main
 * [new branch]      main -> master
----

== 参考

* https://git-scm.com/book/zh/v2/%E8%87%AA%E5%AE%9A%E4%B9%89-Git-Git-%E9%92%A9%E5%AD%90
