= kafka 基本使用 (KRaft，单机)
notfound <notfound@notfound.cn>
1.0, 2022-12-14: init
:sectanchors:

:page-slug: kafka-start
:page-category: kafka

- 系统 Ubuntu 22.04
- Kafka 3.3.1

== 获取 Kafka

下载安装 kafka ：

[source,bash]
----
# 安装 Java 17 (Java 8+)
sudo apt install openjdk-17-jre
# 下载
wget https://downloads.apache.org/kafka/3.3.1/kafka_2.13-3.3.1.tgz
# 解压
sudo tar -zxvf kafka_2.13-3.3.1.tgz -C /opt
# 重命名
sudo mv /opt/kafka_2.13-3.3.1 /opt/kafka
# 修改权限
sudo chown -R $(id -u):$(id -g) /opt/kafka
----

== 运行 Kafka

1. 修改配置文件：
+
.config/kraft/server.properties
[source,properties]
----
# kafka 日志目录
log.dirs=/opt/kafka/kraft-combined-log
# 默认分区数
num.partitions=4
# 禁止自动创建主题
auto.create.topics.enable=false
----
+
2. 生成集群 UUID，同一个集群要使用相同的 UUID ：
+
[source,bash]
----
KAFKA_CLUSTER_ID="$(bin/kafka-storage.sh random-uuid)"
----
+
3. 格式化日志目录，会生成 `bootstrap.checkpoint` 和 `meta.properties` 两个文件，其中 `meta.properties` 包含了集群和节点 ID ：
+
[source,bash]
----
bin/kafka-storage.sh format -t $KAFKA_CLUSTER_ID -c config/kraft/server.properties
----
+
4.  启动 Kafka 服务：
+
[source,bash]
----
# 启动
bin/kafka-server-start.sh -daemon config/kraft/server.properties 
# 停止
bin/kafka-server-stop.sh
----
* `-daemon` 守护进程方式启动，启动日志保存在 `logs` 目录。

== 常用命令

=== 主题操作

[source,bash]
----
export broker=localhost:9092
export topic=quickstart-events

# 创建主题
bin/kafka-topics.sh --bootstrap-server $broker --create --topic $topic
# 查看主题列表
bin/kafka-topics.sh --bootstrap-server $broker --list 
# 查看主题详情
bin/kafka-topics.sh --bootstrap-server $broker --describe --topic $topic
# 增加主题分区数，无法减少
bin/kafka-topics.sh --bootstrap-server $broker --alter --topic $topic --partitions 8
# 删除主题
bin/kafka-topics.sh --bootstrap-server $broker --delete --topic $topic
----

主题详情示例：

[source,text]
----
Topic: quickstart-events        TopicId: o9gbGYYTTmCbF7xToxRD8Q PartitionCount: 4       ReplicationFactor: 1    Configs: segment.bytes=1073741824
        Topic: quickstart-events        Partition: 0    Leader: 1       Replicas: 1     Isr: 1
        Topic: quickstart-events        Partition: 1    Leader: 1       Replicas: 1     Isr: 1
        Topic: quickstart-events        Partition: 2    Leader: 1       Replicas: 1     Isr: 1
        Topic: quickstart-events        Partition: 3    Leader: 1       Replicas: 1     Isr: 1
----

字段说明：

[Attributes]
|===
| 字段 | 描述

| Topic | 主题名
| TopicId | 主题 ID
| PartitionCount | 分区数量
| ReplicationFactor | 复制因子
| segment.bytes | 日志片段大小
| Partition | 分区 ID
| Leader | 首领
| Replicas | 副本集合
| Isr (in-sync replicas) | 同步副本集合
|===


=== 生产、消费

[source,bash]
----
export broker=localhost:9092
export topic=quickstart-events

# 生产
bin/kafka-console-producer.sh --bootstrap-server $broker --topic $topic
This is my first event
This is my second event
# Ctrl+D/Ctrl+C

# 消费
bin/kafka-console-consumer.sh --bootstrap-server $broker --topic $topic --from-beginning
# Ctrl+C
----
* `--from-beginning` 如果消费者还没有一个确定的偏移量来消费，那么从日志中出现的最早消息而不是最新消息开始。

=== 消费者群组

[source,bash]
----
export broker=localhost:9092
export topic=quickstart-events

# 查看消费者群组列表
bin/kafka-consumer-groups.sh --bootstrap-server $broker --list
# 查看消费者群组详情
bin/kafka-consumer-groups.sh --bootstrap-server $broker --describe --group $group
# 删除消费者群组，操作前需要关闭所有消费者
bin/kafka-consumer-groups.sh --bootstrap-server $broker --delete --group $group
----

消费者群组详情示例：

[source,text]
----
GROUP                  TOPIC             PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                           HOST            CLIENT-ID
console-consumer-72635 quickstart-events 0          -               0               -               console-consumer-ecce13ae-89f1-4c61-95df-c5ca2dbb018c /127.0.0.1      console-consumer
console-consumer-72635 quickstart-events 1          -               0               -               console-consumer-ecce13ae-89f1-4c61-95df-c5ca2dbb018c /127.0.0.1      console-consumer
console-consumer-72635 quickstart-events 2          -               0               -               console-consumer-ecce13ae-89f1-4c61-95df-c5ca2dbb018c /127.0.0.1      console-consumer
console-consumer-72635 quickstart-events 3          -               2               -               console-consumer-ecce13ae-89f1-4c61-95df-c5ca2dbb018c /127.0.0.1      console-consumer
----

字段说明：

|===
| 字段 | 描述

| GROUP | 消费者群组名
| TOPIC | 主题名
| PARTITION | 分区 ID
| CURRENT-OFFSET | 消费者群组最近提交的偏移量，也就是消费者在分区里读取的当前位置
| LOG-END-OFFSET | 当前高水位偏移量，也就是最近一个被读取消息的偏移量，同时也是最近一个被提交到集群的偏移量
| LAG | 消费者的 CURRENT-OFFSET 和 broker 的 LOG-END-OFFSET 之间的差距
| CONSUMER-ID | 消费者 ID
| HOST | 客户端主机
| CLIENT-ID | 客户端 ID
|===

=== 动态配置

[source,bash]
----
export broker=localhost:9092
export topic=quickstart-events

# 查看被覆盖的配置
bin/kafka-configs.sh --bootstrap-server $broker --describe --entity-type topics --entity-name $topic
# 查看所有配置
bin/kafka-configs.sh --bootstrap-server $broker --describe --entity-type topics --entity-name $topic --all
----

== 参考

* https://kafka.apache.org/quickstart
* 《Kafka 权威指南》
