= 构建 deb 包
notfound <notfound@notfound.cn>
2.0, 2024-03-08: 更新
:sectanchors:

:page-slug: linux-deb-package-start
:page-category: linux
:page-tags: linux,deb

构建 deb 包。

== 环境准备

=== Debian 12

使用 Debian 12 制作打包镜像：

.bookworm/Dockerfile
[source,dockerfile]
----
FROM debian:bookworm

RUN echo 'deb http://mirrors.cloud.tencent.com/debian bookworm-backports main' > /etc/apt/sources.list.d/backports.list \
    && sources='/etc/apt/sources.list.d/debian.sources' \
    && cp ${sources} ${sources}.bak \
    && sed 's/deb.debian.org/mirrors.cloud.tencent.com/' ${sources}.bak | tee ${sources} \
    && apt-get update \
    && apt-get -y upgrade \
    && apt-get install -y build-essential curl debhelper debmake sudo \
    && rm -rf /var/lib/apt/lists/*
RUN adduser packager --gecos packager \
    && echo 'packager ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
USER packager
ENV DEBEMAIL="packager@notfound.cn" \
    DEBFULLNAME="packager"
WORKDIR /home/packager/debbuild
VOLUME [ "/home/packager/src", "/home/packager/debbuild" ]
----
* backports 软件源的软件比较新；
* 安装打包工具 `debmake` 时会同时安装 `devscripts`、`dpkg-dev` 等相关工具；
* 打包时使用用户 packager，避免使用 root 用户；
* packager 维护工具使用环境变量 `DEBEMAIL` 和 `DEBFULLNAME`；
* 可以考虑将源码、输出目录挂载到容器中，这里并未使用。

构建镜像并运行容器：

[source,bash]
----
# 构建镜像
docker build -t package:bookworm bookworm/
# 运行并进入容器
docker run --interactive --tty --name package-bookworm package:bookworm bash

# 挂载目录方式进入容器
debbuild_dir="${HOME}/debbuild"
mkdir -p ${debbuild_dir}
docker run \
    --name=package-bookworm \
    --volume=.:/home/packager/src \
    --volume=${debbuild_dir}:/home/packager/debbuild \
    --rm \
   package:bookworm bash
----

=== Debian 11

Debian 11 的步骤也类似：

.bullseye/Dockerfile
[source,dockerfile]
----
FROM debian:bullseye

RUN echo 'deb http://mirrors.cloud.tencent.com/debian bullseye-backports main' > /etc/apt/sources.list.d/backports.list \
    && sources='/etc/apt/sources.list' \
    && cp ${sources} ${sources}.bak \
    && sed 's/deb.debian.org/mirrors.cloud.tencent.com/' ${sources}.bak | tee ${sources} \
    && apt-get update \
    && apt-get -y upgrade \
    && apt-get install -y build-essential curl debhelper debmake sudo \
    && rm -rf /var/lib/apt/lists/*
RUN adduser packager --gecos packager \
    && echo 'packager ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
USER packager
ENV DEBEMAIL="packager@notfound.cn" \
    DEBFULLNAME="packager"
WORKDIR /home/packager/debbuild
VOLUME [ "/home/packager/src", "/home/packager/debbuild" ]
----
* 源路径 `sources` 和 debian 12 不一样

[source,bash]
----
docker build -t package:bullseye bullseye/
docker run --interactive --tty --name package-bullseye package:bullseye bash
----

== 打包

这里使用 Debian 12。

=== 获取源码

获取 https://salsa.debian.org/levlaz-guest/debhello[示例源码]：

[source,bash]
----
curl -o debhello-0.0.tar.gz https://salsa.debian.org/levlaz-guest/debhello/-/archive/0.0/debhello-0.0.tar.gz
tar -xzf debhello-0.0.tar.gz
cd debhello-0.0
----

==== Makefile

Makefile 文件内容如下：

.Makefile
[source,makefile]
----
prefix = /usr/local <1>

all: src/hello <2>

src/hello: src/hello.c
        @echo "CFLAGS=$(CFLAGS)" | \
                fold -s -w 70 | \
                sed -e 's/^/# /'
        $(CC) $(CPPFLAGS) $(CFLAGS) $(LDCFLAGS) -o $@ $^

install: src/hello <3>
        install -D src/hello \
                $(DESTDIR)$(prefix)/bin/hello

clean:
        -rm -f src/hello

distclean: clean

uninstall:
        -rm -f $(DESTDIR)$(prefix)/bin/hello

.PHONY: all install clean distclean uninstall <2>
----
<1> 安装文件时使用 `$(prefix)` 的值，以便我们将其设置覆盖为 `/usr`；
<2> make 的默认目标 `all`（排在 `.PHONY` 首位）， 目标 `all` 负责编译整个软件；
<3> 目标 `install` 负责安装，安装文件使用 `$(DESTDIR)` 作为目标系统镜像的路径前缀（`fakeroot`）。

deb 构建时先执行 `make`，再执行 `make install`。

=== debmake

debmake 命令对上游源码树进行 debian 化（debianize），具体来说，是创建一个 debian 目录并仅向该目录中添加各类模板文件。

[source,bash]
----
debmake
----

输出示例：

[source,text]
----
I: set parameters
I: =================================================================
I: package_dir     = /usr/lib/python3/dist-packages
I: base_path       = /usr
I: base_lib_path   = /usr/lib/debmake
I: base_share_path = /usr/share/debmake
I: =================================================================
I: sanity check of parameters
I: pkg="debhello", ver="0.0", rev="1" <1>
I: *** start packaging in "debhello-0.0". ***
I: provide debhello_0.0.orig.tar.gz for non-native Debian package
I: pwd = "/home/packager"
I: $ ln -sf debhello-0.0.tar.gz debhello_0.0.orig.tar.gz <2>
I: pwd = "/home/packager/debhello-0.0"
I: parse binary package settings: 
I: binary package=debhello Type=bin / Arch=any M-A=foreign <3>
I: analyze the source tree
I: build_type = make <4>
I: scan source for copyright+license text and file extensions
I: 100 %, ext = c
I: check_all_licenses
I: ..
I: check_all_licenses completed for 2 files.
I: bunch_all_licenses
I: format_all_licenses
I: make debian/* template files
I: single binary package
I: debmake -x "1" ... <5>
I: creating => debian/control
I: creating => debian/copyright
I: substituting => /usr/share/debmake/extra0/rules
I: creating => debian/rules
I: substituting => /usr/share/debmake/extra0/changelog
I: creating => debian/changelog
I: substituting => /usr/share/debmake/extra1/watch
I: creating => debian/watch
I: substituting => /usr/share/debmake/extra1/README.Debian
I: creating => debian/README.Debian
I: substituting => /usr/share/debmake/extra1source/format
I: creating => debian/source/format
I: substituting => /usr/share/debmake/extra1tests/control
I: creating => debian/source/control
I: substituting => /usr/share/debmake/extra1upstream/metadata
I: creating => debian/upstream/metadata
I: substituting => /usr/share/debmake/extra1tests/control
I: creating => debian/tests/control
I: substituting => /usr/share/debmake/extra1patches/series
I: creating => debian/patches/series
I: substituting => /usr/share/debmake/extra1sourcex/options
I: creating => debian/source/options
I: substituting => /usr/share/debmake/extra1sourcex/local-options
I: creating => debian/source/local-options
I: substituting => /usr/share/debmake/extra1sourcex/patch-header
I: creating => debian/source/patch-header
I: run "debmake -x2" to get more template files
I: $ wrap-and-sort
----
<1> 源码包名称 `debhello`，上游版本 `0.0`，debian 修订版本 `1`
<2> 压缩包建立软连接
<3> 包类型 `bin`
<4> 使用 make 构建
<5> `-x1` 是单个二进制软件包的默认值，后续创建模板文件

==== debian/rules

`debian/rules` 实际构建 Debian 软件包的可执行脚本。

.debian/rules
[source,makefile]
----
#!/usr/bin/make -f

export DH_VERBOSE = 1 <1>
export DEB_BUILD_MAINT_OPTIONS = hardening=+all
export DEB_CFLAGS_MAINT_APPEND  = -Wall -pedantic
export DEB_LDFLAGS_MAINT_APPEND = -Wl,--as-needed

%:
	dh $@

override_dh_auto_install: <2>
	dh_auto_install -- prefix=/usr <3>
----
<1> 显示构建详情；
<2> `override_dh_auto_install` 覆盖 `dh_auto_install` 操作；
<3> 对基于 Makefile 的构建系统来说，`dh_auto_install` 命令所做的基本上就是 `$(MAKE) install DESTDIR=debian/debhello`，这里创建的 `override_dh_auto_install` 目标将其行为修改为 `$(MAKE) install DESTDIR=debian/debhello prefix=/usr`。

查看 dh 相关命令执行顺序：

[source,bash]
----
dh binary --no-act
----

通过 `override_dh_**` 覆盖默认步骤。

==== debian/control

`debian/control` 文件包含了由空行分隔的数块元信息数据，如：构建时的依赖 `Build-Depends`，安装时的依赖 `Depends`。

.debian/control
[source,text]
----
Source: debhello <1>
Section: devel <2>
Priority: optional <3>
Maintainer: Packager <packager@notfound.cn> <4>
Build-Depends: debhelper-compat (= 13) <5>
Standards-Version: 4.5.1 <6>
Homepage: https://notfound.cn
Rules-Requires-Root: no <7>
Vcs-Git: https://salsa.debian.org/levlaz-guest/debhello.git
Vcs-Browser: https://salsa.debian.org/levlaz-guest/debhello

Package: debhello <8>
Architecture: any <9>
Multi-Arch: foreign <10>
Depends: ${misc:Depends}, ${shlibs:Depends} <11>
Description: auto-generated package by debmake <12>
 This Debian binary package was auto-generated by the
 debmake(1) command provided by the debmake package.
----
<1> 源包名称；
<2> 软件包已分类到的应用程序区域；
<3> 软件包的重要性；
<4> 维护者名称和邮箱；
<5> 构建时依赖，如果需要较新的依赖，可以考虑使用 https://backports.debian.org/Instructions/[backports 源]；
<6> 遵循的最新版本的标准；
<7> 构建时是否需要 root；
<8> deb 包的名称；
<9> 体系结构，大部分使用 `any` 或者 `all`，命令 `dpkg-architecture -L` 可列出所有；
<10> 多架构；
<11> 安装时依赖
** `${misc:Depends}`，可用于所有二进制软件包
** `${shlibs:Depends}`，可用于所有含有二进制可执行文件或库的软件包
<12> 软件包描述。

第一节为源码信息，第二节为从源码生成的二进制信息，节于节之间需要一个空行。

一份源码可以打包成多个二进制，此时需要添加多个二进制节，再添加 `debian/_package_.install` 文件指定每个二进制包需要哪些文件。

==== debian/changelog

`debian/changelog` 包含变更日志。

1. 通过 `dch` (`debchange`) 编辑发行版名称为 `UNRELEASED` 部分变更描述；
2. 打包验证通过后，可以通过 `dch -r` 设置发行版，执行命令时回自动将 `UNRELEASED` 修改为 `unstable` 。

[source,changelog]
----
debhello (0.0-1) unstable; urgency=low <1>

  * Initial release.

 -- Packager <packager@notfound.cn>  Sat, 01 Jun 2024 06:26:13 +0000
----
<1> 软件名称、软件版本（上游版本 0.0，debian 版本 1）、发行版、紧急程度。

如果相同源码打包到不同发行版，需要使用不同的 https://unix.stackexchange.com/questions/97289/debian-package-naming-convention[debian 版本名称]，可以参考 https://docs.amd.com/r/en-US/ug1630-kria-som-apps-developer-ubuntu/Naming-Convention-for-Debian-Packages[Naming Convention for Debian Packages] 。

[source,text]
----
<package_name> (<upstream_version>-<debian_revision>+<dist_codename>)
# 如
debhello (0.0-1+bookworm) 
----
* `package_name` 包名
* `upstream_version` 上游软件包版本
* `debian_revision` Debian 修订版本
* `dist_codename` 发行版 codename

=== debuild

debuild 命令是 `dpkg-buildpackage` 命令的一个封装脚本， 基于已 debian 化的源码树构建二进制软件包。

[source,bash]
----
debuild -i -us -uc -b
----
* `-us` (`--unsigned-source`) 不对源码签名
* `-uc` (`--unsigned-changes`) 不对变更签名
* `-b` (`--build=binary`) 打包二进制
* `-i` (`--diff-ignore`) 忽略差异

.输出示例
[source,text]
----
 dpkg-buildpackage -us -uc -ui -i -b
dpkg-buildpackage: info: source package debhello
dpkg-buildpackage: info: source version 0.0-1
dpkg-buildpackage: info: source distribution bookworm
dpkg-buildpackage: info: source changed by Packager <packager@notfound.cn>
 dpkg-source -i --before-build . <1>
dpkg-buildpackage: info: host architecture amd64
 debian/rules clean <2>
dh clean
   dh_auto_clean
	make -j20 distclean
make[1]: Entering directory '/home/packager/debhello-0.0'
rm -f src/hello
make[1]: Leaving directory '/home/packager/debhello-0.0'
   dh_clean
	rm -f debian/debhelper-build-stamp
	rm -rf debian/.debhelper/
	rm -f debian/debhello.debhelper.log
	rm -f -- debian/debhello.substvars debian/files
	rm -fr -- debian/debhello/ debian/tmp/
	find .  \( \( \
		\( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS -o -path .\*/.pc -o -path .\*/_darcs \) -prune -o -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} + \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
 debian/rules binary
dh binary <3>
   dh_update_autotools_config
   dh_autoreconf
   dh_auto_configure
   dh_auto_build
	make -j20 "INSTALL=install --strip-program=true"
make[1]: Entering directory '/home/packager/debhello-0.0'
# CFLAGS=-g -O2 -ffile-prefix-map=/home/packager/debhello-0.0=. 
# -fstack-protector-strong -Wformat -Werror=format-security -Wall 
# -pedantic
cc -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -ffile-prefix-map=/home/packager/debhello-0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -pedantic  -o src/hello src/hello.c
make[1]: Leaving directory '/home/packager/debhello-0.0'
   dh_auto_test
	rm -fr -- /tmp/dh-xdg-rundir-mHhVQbKr
   create-stamp debian/debhelper-build-stamp
   dh_prep
	rm -f -- debian/debhello.substvars
	rm -fr -- debian/.debhelper/generated/debhello/ debian/debhello/ debian/tmp/
   debian/rules override_dh_auto_install
make[1]: Entering directory '/home/packager/debhello-0.0'
dh_auto_install -- prefix=/usr
	install -m0755 -d /home/packager/debhello-0.0/debian/debhello
	make -j20 install DESTDIR=/home/packager/debhello-0.0/debian/debhello AM_UPDATE_INFO_DIR=no "INSTALL=install --strip-program=true" prefix=/usr
make[2]: Entering directory '/home/packager/debhello-0.0'
install -D src/hello \
	/home/packager/debhello-0.0/debian/debhello/usr/bin/hello
make[2]: Leaving directory '/home/packager/debhello-0.0'
make[1]: Leaving directory '/home/packager/debhello-0.0'
   dh_installdocs
	install -m0755 -d debian/debhello/usr/share/doc/debhello
	install -p -m0644 debian/README.Debian debian/debhello/usr/share/doc/debhello/README.Debian
	install -p -m0644 debian/copyright debian/debhello/usr/share/doc/debhello/copyright
   dh_installchangelogs
	install -m0755 -d debian/debhello/usr/share/doc/debhello
	install -p -m0644 debian/.debhelper/generated/debhello/dh_installchangelogs.dch.trimmed debian/debhello/usr/share/doc/debhello/changelog.Debian
   dh_perl
   dh_link
   dh_strip_nondeterminism
   dh_compress
	cd debian/debhello
	chmod a-x usr/share/doc/debhello/changelog.Debian
	gzip -9nf usr/share/doc/debhello/changelog.Debian
	cd '/home/packager/debhello-0.0'
   dh_fixperms
	find debian/debhello ! -type l -a -true -a -true -print0 2>/dev/null | xargs -0r chmod go=rX,u+rw,a-s
	find debian/debhello/usr/share/doc -type f -a -true -a ! -regex 'debian/debhello/usr/share/doc/[^/]*/examples/.*' -print0 2>/dev/null | xargs -0r chmod 0644
	find debian/debhello/usr/share/doc -type d -a -true -a -true -print0 2>/dev/null | xargs -0r chmod 0755
	find debian/debhello -type f \( -name '*.so.*' -o -name '*.so' -o -name '*.la' -o -name '*.a' -o -name '*.js' -o -name '*.css' -o -name '*.scss' -o -name '*.sass' -o -name '*.jpeg' -o -name '*.jpg' -o -name '*.png' -o -name '*.gif' -o -name '*.cmxs' -o -name '*.node' \) -a -true -a -true -print0 2>/dev/null | xargs -0r chmod 0644
	find debian/debhello/usr/bin -type f -a -true -a -true -print0 2>/dev/null | xargs -0r chmod a+x
   dh_missing
   dh_dwz -a
	dwz -- debian/debhello/usr/bin/hello
   dh_strip -a
	install -m0755 -d debian/.debhelper/debhello/dbgsym-root/usr/lib/debug/.build-id/82
	objcopy --only-keep-debug --compress-debug-sections debian/debhello/usr/bin/hello debian/.debhelper/debhello/dbgsym-root/usr/lib/debug/.build-id/82/fad51c1fd0f9430bea7455391597b558a0f0d0.debug
	chmod 0644 -- debian/.debhelper/debhello/dbgsym-root/usr/lib/debug/.build-id/82/fad51c1fd0f9430bea7455391597b558a0f0d0.debug
	strip --remove-section=.comment --remove-section=.note debian/debhello/usr/bin/hello
	objcopy --add-gnu-debuglink debian/.debhelper/debhello/dbgsym-root/usr/lib/debug/.build-id/82/fad51c1fd0f9430bea7455391597b558a0f0d0.debug debian/debhello/usr/bin/hello
	install -m0755 -d debian/.debhelper/debhello/dbgsym-root/usr/share/doc
	ln -s debhello debian/.debhelper/debhello/dbgsym-root/usr/share/doc/debhello-dbgsym
	install -m0755 -d debian/.debhelper/debhello
   dh_makeshlibs -a
	rm -f debian/debhello/DEBIAN/shlibs
   dh_shlibdeps -a
	install -m0755 -d debian/debhello/DEBIAN
	dpkg-shlibdeps -Tdebian/debhello.substvars debian/debhello/usr/bin/hello
   dh_installdeb
	install -m0755 -d debian/debhello/DEBIAN
   dh_gencontrol
	install -m0755 -d debian/debhello/DEBIAN
	echo misc:Depends= >> debian/debhello.substvars
	echo misc:Pre-Depends= >> debian/debhello.substvars
	install -m0755 -d debian/.debhelper/debhello/dbgsym-root/DEBIAN
	dpkg-gencontrol -pdebhello -ldebian/changelog -Tdebian/debhello.substvars -Pdebian/.debhelper/debhello/dbgsym-root -UPre-Depends -URecommends -USuggests -UEnhances -UProvides -UEssential -UConflicts -DPriority=optional -UHomepage -UImportant -UBuilt-Using -DAuto-Built-Package=debug-symbols -UProtected -DPackage=debhello-dbgsym "-DDepends=debhello (= \${binary:Version})" "-DDescription=debug symbols for debhello" -DBuild-Ids=82fad51c1fd0f9430bea7455391597b558a0f0d0 -DSection=debug -UMulti-Arch -UReplaces -UBreaks
	chmod 0644 -- debian/.debhelper/debhello/dbgsym-root/DEBIAN/control
	dpkg-gencontrol -pdebhello -ldebian/changelog -Tdebian/debhello.substvars -Pdebian/debhello
	chmod 0644 -- debian/debhello/DEBIAN/control
   dh_md5sums
	install -m0755 -d debian/debhello/DEBIAN
	cd debian/debhello >/dev/null && xargs -r0 md5sum | perl -pe 'if (s@^\\@@) { s/\\\\/\\/g; }' > DEBIAN/md5sums
	chmod 0644 -- debian/debhello/DEBIAN/md5sums
	install -m0755 -d debian/.debhelper/debhello/dbgsym-root/DEBIAN
	cd debian/.debhelper/debhello/dbgsym-root >/dev/null && xargs -r0 md5sum | perl -pe 'if (s@^\\@@) { s/\\\\/\\/g; }' > DEBIAN/md5sums
	chmod 0644 -- debian/.debhelper/debhello/dbgsym-root/DEBIAN/md5sums
   dh_builddeb
	dpkg-deb --root-owner-group --build debian/.debhelper/debhello/dbgsym-root ..
	dpkg-deb --root-owner-group --build debian/debhello ..
dpkg-deb: building package 'debhello' in '../debhello_0.0-1_amd64.deb'.
dpkg-deb: building package 'debhello-dbgsym' in '../debhello-dbgsym_0.0-1_amd64.deb'.
 dpkg-genbuildinfo --build=binary -O../debhello_0.0-1_amd64.buildinfo <4>
 dpkg-genchanges --build=binary -O../debhello_0.0-1_amd64.changes <5>
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source -i --after-build .
dpkg-buildpackage: info: binary-only upload (no source included)
Now running lintian debhello_0.0-1_amd64.changes ...
E: debhello changes: bad-distribution-in-changes-file bookworm
E: debhello: changelog-is-dh_make-template [usr/share/doc/debhello/changelog.Debian.gz:1]
E: debhello: copyright-file-contains-full-gpl-license
E: debhello: copyright-not-using-common-license-for-gpl
W: debhello: copyright-has-url-from-dh_make-boilerplate
W: debhello: initial-upload-closes-no-bugs [usr/share/doc/debhello/changelog.Debian.gz:1]
W: debhello: no-manual-page [usr/bin/hello]
W: debhello: readme-debian-contains-debmake-template [usr/share/doc/debhello/README.Debian]
W: debhello: wrong-bug-number-in-closes #nnnn [usr/share/doc/debhello/changelog.Debian.gz:3]
Finished running lintian.
----
<1> 应用 Debian 补丁，除非它们已被应用
<2> 执行清理 `fakeroot debian/rules clean`
<3> 构建源码
<4> 产生一个 *.buildinfo 文件
<5> 产生一个 *.changes 文件

可在父目录看到生成的 deb 包。

== 二进制拆包

假设打包生成 hello 和 hello2 两个文件，需要单独打包。

修改 `Makefile` 生成新的二进制文：

.Makefile
[source,diff]
----
@@ -11,6 +11,8 @@ src/hello: src/hello.c
 install: src/hello
        install -D src/hello \
                $(DESTDIR)$(prefix)/bin/hello
+       install -D src/hello \
+               $(DESTDIR)$(prefix)/bin/hello2
 
 clean:
        -rm -f src/hello
----
* 新增一个二进制文件 `hello2`。

修改 `debian/control` 提供二进制包信息：

.debian/control
[source,diff]
----
@@ -16,3 +16,11 @@ Depends: ${misc:Depends}, ${shlibs:Depends}
 Description: auto-generated package by debmake
  This Debian binary package was auto-generated by the
  debmake(1) command provided by the debmake package.
+
+Package: debhello2
+Architecture: any
+Multi-Arch: foreign
+Depends: ${misc:Depends}, ${shlibs:Depends}
+Description: auto-generated package by debmake
+ This Debian binary package was auto-generated by the
+ debmake(1) command provided by the debmake package.
----
* 新增二进制包 `debhello2`。

指定 `debhello` 包文件：

.debian/debhello.install
[source,text]
----
/usr/bin/hello
----
* 只打包 `hello`

指定 `debhello2` 包文件：

.debian/debhello2.install
[source,text]
----
/usr/bin/hello2
----
* 只打包 `hello2`

执行 `debuild -i -us -uc -b` 可以看到生成了多个 deb 包。

== 进阶

=== dh_installsystemd

安装时添加 systemd 文件。

添加 `debian/_package_.service` 时，会自动将文件添加到 `/lib/systemd/system/_package_.service`。

参考：

* man dh_installsystemd(1)
* man dh_systemd_enable(1)
* man dh_systemd_start(1)
* https://wiki.debian.org/Teams/pkg-systemd/Packaging

=== dh_installdeb

安装 deb 过程中执行某些脚本。

* `debian/_package_.prerm` 删除前；
* `debian/_package_.preinst` 安装前；
* `debian/_package_.postrm` 删除后，可以执行删除胚子文件、删除用户等操作，如 https://salsa.debian.org/ssh-team/openssh/-/blob/master/debian/openssh-server.postrm[openssh-server.postrm]；
* `debian/_package_.postinst` 安装后，可以执行创建配置文件、创建用户等操作，如： https://salsa.debian.org/ssh-team/openssh/-/blob/master/debian/openssh-server.postinst[openssh-server.postinst]。

从 debhello_0.0-1_amd64.deb 升级到 debhello_0.0-2_amd64.deb：

[source,text]
----
$ sudo dpkg -i --debug=20 ../debhello_0.0-2_amd64.deb 
(正在读取数据库 ... 系统当前共安装有 305456 个文件和目录。)
准备解压 ../debhello_0.0-2_amd64.deb  ...
prerm: arg1=upgrade, arg2=0.0-2, arg3=, arg4=, arg5= <1>
preinst: arg1=upgrade, arg2=0.0-1, arg3=0.0-2, arg4=, arg5= <2>
正在解压 debhello (0.0-2) 并覆盖 (0.0-1) ...
postrm: arg1=upgrade, arg2=0.0-2, arg3=, arg4=, arg5= <3>
正在设置 debhello (0.0-2) ...
postinst: arg1=configure, arg2=0.0-1, arg3=, arg4=, arg5= <4>
debhello.service is a disabled or a static unit not running, not starting it.
----
<1> 旧包删除前：old-prerm upgrade new-version
<2> 新包安装前：new-preinst upgrade old-version new-version
<3> 旧包删除后：old-postrm upgrade new-version
<4> 新包安装后：postinst configure old-version

参考：

* man dh_installdeb(1)
* man deb-prerm(1)
* man deb-preinst(1)
* man deb-postrm(1)
* man deb-postinst(1)

== dpkg

dpkg Debian 包管理工具。

[source,bash]
----
# 查看 deb 内容
dpkg --contents debhello_0.0-1_amd64.deb
# 查看 control 信息
dpkg --field debhello_0.0-1_amd64.deb
# 安装
sudo dpkg -i debhello_0.0-1_amd64.deb
# 查看已安装包文件列表
dpkg --listfiles debhello
# 根据文件查询包
dpkg --search /usr/bin/hello
# 卸载
sudo dpkg --remove debhello
----

== 参考

* https://www.debian.org/doc/manuals/debmake-doc/index.zh-cn.html
* https://www.debian.org/doc/debian-policy/index.html
