= 使用 reprepro 制作 apt 源
notfound <notfound@notfound.cn>
1.0, 2024-01-29: init

:page-slug: linux-reprepro-install
:page-category: linux 
:page-tags:  linux,deb,gpg

使用 apt 分发您自己的 Debian 软件包。

基本工作流程：

1. **构建机器** 执行 debuild 构建 deb 包；
2. **构建机器** 执行 dput 上传包到 **APT 服务器**（通过 Nginx WebDAV 上传文件）；
3. **APT 服务器** 执行 reprepro 添加 deb 包。

系统环境：Debian 12/ Ubuntu 22.04

== reprepro

=== GPG 密钥对

生成 GPG 密钥：

[source,bash]
----
# 安装 gnupg
sudo apt install gnupg
# 生成 GPG 密钥
gpg --full-generate-key
# 列出 GPG
gpg --list-secret-key --with-subkey-fingerprint
----

导出 GPG 公钥:

[source,bash]
----
mkdir -p /var/www/packages
gpg --armor --output /var/www/packages/public.gpg --export 6B06EA99E7DA2B503B6F189AD6CB181E40E820EF
----

=== 安装

[source,bash]
----
sudo apt install reprepro
----

=== 配置

创建目录：

[source,bash]
----
# debian/ubuntu apt 源数据
mkdir -p /var/www/packages/{debian,ubuntu}

# debian 12 (bookworm) / 11 (bullseye) 新到来的 deb 包
mkdir -p /var/www/packages/incoming/debian/{bullseye,bookworm}
mkdir -p /var/www/packages/incoming/debian/{bullseye-temp,bookworm-temp}

# ubuntu 20.04 (focal) / 22.04 (jammy) 新到来的 deb 包
mkdir -p /var/www/packages/incoming/ubuntu/{focal,jammy}
mkdir -p /var/www/packages/incoming/ubuntu/{focal-temp,jammy-temp}
----

Nginx WebDAV 以 www-data 用户身份在 incoming 目录下创建文件，reprepro 命令也需要读、删这些文件，因此可以将当前用户添加到 www-data 组，同时供给组添加写权限：

[source,bash]
----
sudo usermod -a -G www-data $USER
chmod g+w -R /var/www/packages/incoming
sudo chown www-data:www-data -R /var/www/packages/incoming
----

新的 deb 包放到 incoming 目录，之后由 reprepro 处理。

==== Debian

Debian 相关配置位于目录 `/var/www/packages/debian`。

配置发行版 debian 12 和 debian 11：

.conf/distributions
[source,conf]
----
Origin: packages.notfound.cn
Label: notfound
Codename: bookworm
Architectures: amd64 arm64
Components: main
Description: Notfound apt repository
SignWith: 6B06EA99E7DA2B503B6F189AD6CB181E40E820EF

Origin: packages.notfound.cn
Label: notfound
Codename: bullseye
Architectures: amd64 arm64
Components: main
Description: Notfound apt repository
SignWith: 6B06EA99E7DA2B503B6F189AD6CB181E40E820EF
----
* `Codename` 通过命令 `lsb_release --short --codename` 可以查看：
** `bookworm`: Debian 12
** `bullseye`: Debian 11
* `Architectures` 体系结构，命令 `dpkg-architecture -L` 可列出所有值；
* `SignWith` GPG KEY ID，用于 GPG 签名。

配置 reprepro 参数：

.conf/options
[source,conf]
----
verbose
basedir /var/www/packages/debian
ask-passphrase
----
* `verbose` 显示详情；
* `basedir` Debian 包目录；
* `ask-passphrase` 需要输入 gpg 密码。

配置 incoming：

.conf/incoming 
[source,conf]
----
Name: bookworm
IncomingDir: /var/www/packages/incoming/debian/bookworm
TempDir: /var/www/packages/incoming/debian/bookworm-temp
Allow: bookworm
Default: bookworm
Permit: unused_files
Cleanup: unused_files on_deny on_error

Name: bullseye
IncomingDir: /var/www/packages/incoming/debian/bullseye
TempDir: /var/www/packages/incoming/debian/bullseye-temp
Allow: bullseye
Default: bullseye
Permit: unused_files
Cleanup: unused_files on_deny on_error
----
* `Name` 规则集名称；
* `IncomingDir` 用来扫描 `.changes` 文件的目录；
* `TempDir` 处理过程中的临时目录；
* `Allow` 允许的发行版本；
* `Default` 未通过 `Allow` 参数时的默认发行版；
* `Permit` 允许的出现未使用的文件（unused_files）；
* `Cleanup` 未使用（unused_files)、拒绝处理（on_deny）、处理出错（on_error）时文件都会被清理。

==== Ubuntu

和 Debian 类似。

=== 添加 deb 包

==== 方法一

通过 `includedeb` 直接添加：

[source,bash]
----
reprepro --basedir /var/www/packages/debian includedeb bookworm ~/bookworm/debhello_0.0-1_amd64.deb
----

==== 方法二

将 .changes 以及 `.changes` 中指定的相关文件放到 incoming 目录，执行：

[source,bash]
----
reprepro --basedir /var/www/packages/debian processincoming bookworm
----

这些文件可以在 debuild 后通过 `dput` 上传，见后文。

==== reprepro 命令

[source,bash]
----
# 列出
reprepro list bookworm
# 移除
reprepro remove bookworm debhello
# 删除所有不在发行版中的包数据库
reprepro clearvanished
----

== 配置 Nginx

Nginx 两个功能：

1. 提供 APT 源数据；
2. 开启 WebDAV 功能，以支持 dput 上传 deb 包，上传的包之后由 reprepro 进行处理。

添加文件 `/etc/nginx/conf.d/notfound.conf`：

./etc/nginx/conf.d/notfound.conf
[source,nginx]
----
server {
    listen 80;

    server_name packages.notfound.cn;

    root /var/www/packages;

    location / {
        autoindex on;
    }

    location ~ /(.*)/conf {
        deny all;
    }

    location ~ /(.*)/db {
        deny all;
    }

    location ~ /incoming/debian/(bookworm|bullseye)/ {
        client_body_temp_path   /var/www/packages/client_temp;
        create_full_put_path    on;
        dav_access              user:rw group:rw all:r;
        dav_methods             PUT DELETE MKCOL COPY MOVE;
    }

    location ~ /incoming/ubuntu/(jammy|focal)/ {
        client_body_temp_path   /var/www/packages/client_temp;
        create_full_put_path    on;
        dav_access              user:rw group:rw all:r;
        dav_methods             PUT DELETE MKCOL COPY MOVE;
    }
}
----
* root 目录为 apt 目录；
* 开启了目录浏览功能；
* 禁止访问 `conf` 和 `deb`
* 配置 Nginx WebDAV，只允许访问指定的目录（这里未配置认证，建议开启认证以及使用 HTTPS）

== dput

通过 dput 可上传打包的文件。

dput 支持 ftp、http(s)、scp、sftp、rsync 和 local 方式上传文件。

=== 配置

.~/.dput.cf
[source,conf]
----
[DEFAULT]
default_host_main       = notfound

[notfound]
fqdn                    = packages.notfound.cn
method                  = http
incoming                = /incoming/debian/bookworm
----

参考： man dput.cf

=== 上传

[source,bash]
----
dput -u debhello_0.0-1_amd64.changes
----

== 客户端

添加 GPG Key：

[source,bash]
----
sudo mkdir -p /etc/apt/keyrings
sudo curl -sSL http://packages.notfound.cn/public.gpg -o /etc/apt/keyrings/notfound.asc
----

添加 apt 源：

./etc/apt/sources.list.d/notfound.list
[source,conf]
----
# debian 12
deb [signed-by=/etc/apt/keyrings/notfound.asc] http://packages.notfound.cn/debian bookworm main

# deiban 11
deb [signed-by=/etc/apt/keyrings/notfound.asc] http://packages.notfound.cn/debian bullseye main
----

安装 debhello：

[source,bash]
----
sudo apt update
sudo apt install debhello
----

== 包命名约定

deb 包名称相同但内容不同时，无法重复添加，即使是不同的发行版：

[source,text]
----
$ reprepro includedeb bullseye deb/bullseye/debhello_0.0-1_amd64.deb
deb/bullseye/debhello_0.0-1_amd64.deb: component guessed as 'main'
ERROR: 'deb/bullseye/debhello_0.0-1_amd64.deb' cannot be included as 'pool/main/d/debhello/debhello_0.0-1_amd64.deb'.
Already existing files can only be included again, if they are the same, but:
md5 expected: 937114b8826ea3441f2eb3a196db1a8d, got: 169429e1b925b065b866e714ffd10a09
sha1 expected: 1824644849af1b8cca7234a2406d0052163ae27d, got: bedd3f062023aef802e0ae153b2be31e351d8a9d
sha256 expected: 38749fd54428945ec9a93b01ea92c6e153b8592b7ebf786a322d6e7408817a8a, got: fcdc9cfc23f1ca8b5082e0d957ee225bc1219405ddbfc1aa2873088ca5076f89
size expected: 14392, got: 14512
There have been errors!
----

如果相同的源码需要打包到不同发行版 `Codename`，需要修改 `debian/changelog` 中的版本信息改变 deb 包名称。

=== Debian/Ubuntu 命名约定

通过变更日志查看现有的包命名规则：

[source,bash]
----
apt changelog openjdk-17-jdk
apt changelog curl
----

结果：

[source,text]
----
# Debian 12 查看官方包命名：
openjdk-17 (17.0.11+9-1~deb12u1) bookworm-security; urgency=medium
curl (7.88.1-10+deb12u5) bookworm-security; urgency=high

# Debian 11 查看官方包命名：
openjdk-17 (17.0.11+9-1~deb11u1) bullseye-security; urgency=medium
curl (7.74.0-1.3+deb11u11) bullseye-security; urgency=high

# Ubuntu 22.04
openjdk-17 (17.0.10+7-1~22.04.1) jammy-security; urgency=high
curl (7.81.0-1ubuntu1.16) jammy-security; urgency=medium

# ubuntu 20.04
openjdk-17 (17.0.10+7-1~20.04.1) focal-security; urgency=high
curl (7.68.0-1ubuntu2.22) focal-security; urgency=medium
----

看上去并没有一个强制标识 codename 的统一规范。

可以参考 https://docs.amd.com/r/en-US/ug1630-kria-som-apps-developer-ubuntu/Naming-Convention-for-Debian-Packages[Naming Convention for Debian Packages] 使用规则：

[source,text]
----
<package_name> (<upstream_version>-<debian_revision>+<dist_codename>)
# 如
debhello (0.0-1+bookworm) 
debhello (0.0-1+bullseye) 
----
* `package_name` 包名
* `upstream_version` 上游软件包版本
* `debian_revision` Debian 修订版本
* `dist_codename` 发行版 codename

修改 `debian/changelog` 后重新打包。


== 参考

* https://wiki.debian.org/DebianRepository/SetupWithReprepro
* http://blog.jonliv.es/blog/2011/04/26/creating-your-own-signed-apt-repository-and-debian-packages/
* https://docs.amd.com/r/en-US/ug1630-kria-som-apps-developer-ubuntu/Build-Debian-Binary-File
* https://unix.stackexchange.com/questions/97289/debian-package-naming-convention
