= 使用 OpenSSL 生成 Nginx 证书
notfound <notfound@notfound.cn>
2.0, 2021-11-21: 创建
:sectanchors:

:page-slug: linux-ssl-nginx
:page-category: linux
:page-tags: nginx,ssl

系统环境：Ubuntu 22.04

== 方法 1：自签名证书

生成服务器私钥：

[source,bash]
----
export domain="example.test"
openssl genrsa -out ${domain}.key 2048
----

生成证书签名请求：

[source,bash]
----
openssl req -new -key ${domain}.key -out ${domain}.csr
----
* `Common Name (eg, your name or your server's hostname)` 填写域名 `example.test`

使用证书签名请求以及私钥签发证书：

[source,bash]
----
openssl x509 -req -days 365 -in ${domain}.csr -signkey ${domain}.key -out ${domain}.crt
----

== 方法 2：生成自签名 CA 证书

=== CA

测试域名为 `example.test`

创建 CA 目录：

[source,bash]
----
mkdir -p ssl/demoCA/{certs,newcerts,crl,private}
cd ssl
touch demoCA/index.txt
echo "01" > demoCA/serial
cp /etc/ssl/openssl.cnf .
----

修改 `req_distinguished_name` 段如 `countryName_default` 等默认值避免反复填写相关信息：

.openssl.cnf
[source,diff]
----
 [ req_distinguished_name ]
 countryName                    = Country Name (2 letter code)
-countryName_default            = AU
+countryName_default            = CN

 stateOrProvinceName            = State or Province Name (full name)
-stateOrProvinceName_default    = Some-State
+stateOrProvinceName_default    = GuangDong

 localityName                   = Locality Name (eg, city)
+localityName_default           = ShenZhen

 0.organizationName             = Organization Name (eg, company)
-0.organizationName_default     = Internet Widgits Pty Ltd
+0.organizationName_default     = Development and Test

 organizationalUnitName         = Organizational Unit Name (eg, section)
-#organizationalUnitName_default        =
+organizationalUnitName_default = Development and Test

 commonName                     = Common Name (e.g. server FQDN or YOUR name)
 commonName_max                 = 64

 emailAddress                   = Email Address
+emailAddress_default           = admin@ca.test
----

生成 CA 私钥和证书：

[source,bash]
----
openssl req -new -x509 -days 3650 -newkey rsa:2048 \
  -keyout demoCA/private/cakey.pem \
  -out demoCA/cacert.pem \
  -config openssl.cnf
----
* 证书有效期 3560 天
* 输出目录与配置文件一致
* 注意输入域名 `Common Name (eg, your name or your server's hostname) []:ca.test`

查看 key 和证书：

[source,bash]
----
# 查看 rsa 私钥
openssl rsa -noout -text -in demoCA/private/cakey.pem
# 查看证书
openssl x509 -noout -text -in demoCA/cacert.pem
# 移除私钥密码
openssl rsa -in demoCA/cacert.pem -out demoCA/cacert.key
----

目录结构：

[source,text]
----
ssl
├── demoCA
│   ├── cacert.pem
│   ├── certs
│   ├── crl
│   ├── index.txt
│   ├── newcerts
│   ├── private
│   │   └── cakey.pem
│   └── serial
└── openssl.cnf
----

=== 客户端

编辑文件 `openssl.cnf`：

.openssl.cnf
[source,conf]
----
[ req ]
# 移除 req_extensions 注释
req_extensions = v3_req # The extensions to add to a certificate request

[ v3_req ]
# 新增 subjectAltName
subjectAltName = @alt_names

[ usr_cert ]
# 新增 subjectAltName
subjectAltName = @alt_names

# 新增 alt_names 段，DNS 必须和域名一致。*.example.test 表示可二级泛域名
[ alt_names ]
DNS.1 = example.test
DNS.2 = *.example.test
----
* 浏览器验证证书时需要该配置生成的信息
* 证书可支持 `example.test` 以及 `*.example.test`

生成客户端私钥：

[source,bash]
----
export domain="example.test"
openssl genrsa -out ${domain}.key 2048
----

生成证书签名请求：

[source,bash]
----
openssl req -new -key ${domain}.key -out ${domain}.csr -config openssl.cnf
----
* 注意输入域名 `Common Name (eg, your name or your server's hostname) []: example.test`

使用 CA 根证书签发客户端证书：

[source,bash]
----
openssl ca -in ${domain}.csr -out ${domain}.crt -config openssl.cnf
----
* 注意检查 `509v3 Subject Alternative Name` 是否和域名一致

== 方法 3：多级证书

创建目录：

[source,bash]
----
mkdir -p ssl/{ca1.demo.com,ca2.demo.com}/{certs,newcerts,crl,private}
cd ssl
----

目录结构：

[source,text]
----
ssl
├── ca1.demo.com
│   ├── certs
│   ├── crl
│   ├── newcerts
│   └── private
└── ca2.demo.com
    ├── certs
    ├── crl
    ├── newcerts
    └── private
----

=== 根 CA

配置：

[source,bash]
----
touch ca1.demo.com/index.txt
echo "01" > ca1.demo.com/serial

cp /etc/ssl/openssl.cnf .
----

修改 `openssl.cnf`，修改所有的 `demoCA`, 和 `CA_default` 域的 `x509_extensions`：

[source,diff]
----
 [ CA_default ]
 ... 
-dir            = ./demoCA              # Where everything is kept
+dir            = ./ca1.demo.com        # Where everything is kept
 ... 
-x509_extensions        = usr_cert      # The extensions to add to the cert
+x509_extensions        = v3_ca         # The extensions to add to the cert
 ... 
-dir            = ./demoCA              # TSA root directory
+dir            = ./ca1.demo.com        # TSA root directory
----

生成私钥和证书：

[source,bash]
----
openssl req -config openssl.cnf \
  -new -x509 -newkey rsa:2048 \
  -keyout ca1.demo.com/private/cakey.pem \
  -out ca1.demo.com/cacert.pem
----

=== 二级 CA

配置：

[source,bash]
----
touch ca2.demo.com/index.txt
echo "01" > ca2.demo.com/serial
----

生成私钥和证书请求：

[source,bash]
----
openssl genrsa -out ca2.demo.com/private/cakey.pem 2048
openssl req -config openssl.cnf \
  -new -key ca2.demo.com/private/cakey.pem \
  -out ca2.demo.com/ca.csr
----

通过根 CA 对二级 CA 证书请求进行签名：

[source,bash]
----
openssl ca -config openssl.cnf -in ca2.demo.com/ca.csr -out ca2.demo.com/cacert.pem
----

修改 `openssl.cnf`，替换全部 `ca1.demo.com` 和 `CA_default` 段的 `x509_extensions`，后续操作使用 `ca2.demo.com`：

[source,diff]
----
 [ CA_default ]
 ...
-dir            = ./ca1.demo.com                # Where everything is kept
+dir            = ./ca2.demo.com                # Where everything is kept
 ...
-x509_extensions        = v3_ca                 # The extensions to add to the cert
+x509_extensions        = usr_cert              # The extensions to add to the cert
 ...
-dir            = ./ca1.demo.com                # TSA root directory
+dir            = ./ca2.demo.com                # TSA root directory
----

=== 客户端

[source,bash]
----
export domain=demo.com
mkdir $domain
openssl genrsa -out $domain/$domain.key 2048
openssl req -config openssl.cnf -new -key $domain/$domain.key -out $domain/$domain.csr
----

客户端签名：

[source,bash]
----
openssl ca -config openssl.cnf \
  -in $domain/$domain.csr \
  -out $domain/$domain.crt
----

=== 多域名证书

修改 `openssl.conf`：

[source,diff]
----
 [ usr_cert ]
 ...
-# subjectAltName=email:copy
+subjectAltName=DNS:demo.io,DNS:*.demo.io
----
* 证书可对 demo.io 和 demo.io 二级域名生效

之后执行证书生成操作。

=== 问题

* 报错 curl: (60) SSL certificate problem: unable to get local issuer certificate
+
自签名证书无法通过网络获取证书链，因此在配置 Nginx 时，需要将证书链上除根证书以外的所有证书放到同一个证书文件。
+
这里需要将 `demo.com/demo.com.crt` 和 `ca2.demo.com/cacert.pem` 放到一起：
+
[source,bash]
----
# 合并两个文件内容
cat demo.com/demo.com.crt ca2.demo.com/cacert.pem > demo.com.crt
----

== 配置 Nginx

复制证书：

[source,bash]
----
sudo mkdir /etc/nginx/certs.d/
sudo cp ${domain}.crt /etc/nginx/certs.d
sudo cp ${domain}.key /etc/nginx/certs.d
----

以域名 example.test 为例，添加 Nginx 配置文件：

./etc/nginx/conf.d/example.test.conf
[source,nginx]
----
server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;

  ssl_certificate /etc/nginx/certs.d/example.test.crt;
  ssl_certificate_key /etc/nginx/certs.d/example.test.key;

  server_name example.test;

  root /var/www/html;

  location / {
    try_files $uri $uri/ =404;
  }
}
----

配置多级证书时，需要将中间证书也添加到证书文件，根证书可选。

测试证书有效性：

[source,bash]
----
openssl s_client -connect example.test:443
----

== 添加 CA 到 Linux 系统

可直接通过 HTTPS 请求获取证书：

[source,bash]
----
# 执行命令后，输入 quit
openssl s_client -showcerts -servername example.test -connect example.test:443 > example_test_0.pem

openssl x509 -inform PEM -in example_test_0.pem -text -out example_test.pem
----

添加 CA 根证书：

[source,bash]
----
# Ubuntu 22.04
sudo cp demoCA/cacert.pem /usr/local/share/ca-certificates/ca.test.crt
sudo update-ca-certificates
----

使用 curl 命令时，CA 证书会生效：

[source,bash]
----
curl -v -I https://example.test
----

=== Linux 浏览器

在 Linux上，Chromium (Chrome Edge) 使用 NSS 共享数据库，需要安装：

[source,bash]
----
sudo apt install libnss3-tools
----

[source,bash]
----
# 列出所有证书
certutil -d sql:$HOME/.pki/nssdb -L
# 列出证书的详细信息
certutil -d sql:$HOME/.pki/nssdb -L -n <certificate nickname>
# 添加 CA 根证书
certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n "ca.test" -i demoCA/cacert.pem

# 添加 CA 根证书
certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n "ca1.demo.com" -i ca1.demo.com/cacert.pem
# 添加 CA 中间证书
certutil -d sql:$HOME/.pki/nssdb -A -t ",,"  -n "ca2.demo.com" -i ca2.demo.com/cacert.pem
# 删除 CA 证书
certutil -d sql:$HOME/.pki/nssdb -D -n "ca2.demo.com"
----

生成的证书需要 subjectAltName (X509v3 Subject Alternative Name)，否则浏览器无法验证通过。

== 参考

* https://nginx.org/en/docs/http/configuring_https_servers.html
* https://docs.fedoraproject.org/en-US/quick-docs/using-shared-system-certificates/
* https://www.linode.com/docs/guides/using-openssls-subjectaltname-with-multiple-site-domains/
* https://curl.se/docs/sslcerts.html
* https://chromium.googlesource.com/chromium/src/+/master/docs/linux/cert_management.md
* https://www.rfc-editor.org/rfc/rfc6761.html
