= 使用 OpenSSL 生成 Nginx 证书
notfound <notfound@notfound.cn>
1.0, 2021-11-21: 创建
:sectanchors:

:page-slug: linux-ssl-nginx
:page-category: nginx

* fedora 35

== 自签名证书

. 生成服务器私钥：
+
[source,bash]
----
openssl genrsa -out example_com.key 2048
----
+
. 生成证书签名请求：
+
[source,bash]
----
openssl req -new -key example_com.key -out example_com.csr
----
* `Common Name (eg, your name or your server's hostname)` 填写域名 `example.com`
+
. 使用证书签名请求以及私钥签发证书
+
[source,bash]
----
openssl x509 -req -days 365 -in example_com.csr -signkey example_com.key -out example_com.crt
----

== 生成自签名 CA 证书

在目录 ssl 中执行操作

=== CA

测试域名为 `example.com`

. 创建 CA 目录：
+
[source,bash]
----
mkdir -p demoCA/{certs,newcerts,crl,private}
touch demoCA/index.txt
echo "01" > demoCA/serial
----
+
. 配置 openssl：
+
[source,bash]
----
cp /etc/ssl/openssl.cnf .
sed -i 's/\/etc\/pki\/CA/demoCA/g' openssl.cnf
----
* CA 目录从 `/etc/pki/CA` 改为 `demoCA`
+
. 生成 CA 私钥和证书：
+
[source,bash]
----
openssl req -new -x509 -days 365 -newkey rsa:2048 -keyout demoCA/private/cakey.pem \
  -out demoCA/cacert.pem -config openssl.cnf
----
* 证书有效期 356 天
* 输出目录与配置文件一致
* 注意输入域名 `Common Name (eg, your name or your server's hostname) []:example.com`
+
. 查看 key 和证书：
+
[source,bash]
----
# 查看 rsa 私钥
openssl rsa -noout -text -in demoCA/private/cakey.pem
# 查看证书
openssl x509 -noout -text -in demoCA/cacert.pem
----

目录结构

....
ssl
├── demoCA
│   ├── cacert.pem
│   ├── certs
│   ├── crl
│   ├── index.txt
│   ├── newcerts
│   ├── private
│   │   └── cakey.pem
│   └── serial
└── openssl.cnf
....

=== 客户端

. 生成客户端私钥：
+
[source,bash]
----
openssl genrsa -out example_com.key 2048
----
+
. 生成证书签名请求：
+
[source,bash]
----
openssl req -new -key example_com.key -out example_com.csr -config openssl.cnf
----
* 注意输入域名 `Common Name (eg, your name or your server's hostname) []: example.com`
+
. 使用 CA 根证书签发客户端证书：
+
[source,bash]
----
openssl ca -in example_com.csr -out example_com.crt -config openssl.cnf
----

== 多级证书

创建目录：

[source,bash]
----
mkdir -p ssl/{ca1.demo.com,ca2.demo.com}/{certs,newcerts,crl,private}
----

目录结构：

[source,text]
----
ssl
├── ca1.demo.com
│   ├── certs
│   ├── crl
│   ├── newcerts
│   └── private
└── ca2.demo.com
    ├── certs
    ├── crl
    ├── newcerts
    └── private
----

=== 根 CA

在目录 `ssl` 中执行

. 配置
+
[source,bash]
----
touch ca1.demo.com/index.txt
echo "01" > ca1.demo.com/serial

cp /etc/ssl/openssl.cnf .
----
+
. 修改 `openssl.cnf`，修改所有的 `demoCA`, 和 `CA_default` 段的 `x509_extensions`：
+
[source,diff]
----
 [ CA_default ]
 ... 
-dir            = ./demoCA              # Where everything is kept
+dir            = ./ca1.demo.com        # Where everything is kept
 ... 
-x509_extensions        = usr_cert      # The extensions to add to the cert
+x509_extensions        = v3_ca         # The extensions to add to the cert
 ... 
-dir            = ./demoCA              # TSA root directory
+dir            = ./ca1.demo.com        # TSA root directory
----
+
. 可以先修改 `req_distinguished_name` 段如 `countryName_default` 等默认值避免反复填写：
[source,diff]
----
 [ req_distinguished_name ]
 countryName                    = Country Name (2 letter code)
-countryName_default            = AU
+countryName_default            = CN
 
 stateOrProvinceName            = State or Province Name (full name)
-stateOrProvinceName_default    = Some-State
+stateOrProvinceName_default    = GuangDong
 
 localityName                   = Locality Name (eg, city)
+localityName_default           = ShenZhen
 
 0.organizationName             = Organization Name (eg, company)
-0.organizationName_default     = Internet Widgits Pty Ltd
+0.organizationName_default     = demo
----
. 然后生成私钥和证书：
+
[source,bash]
----
openssl req -config openssl.cnf \
  -new -x509 -newkey rsa:2048 \
  -keyout ca1.demo.com/private/cakey.pem \
  -out ca1.demo.com/cacert.pem
----

=== 二级 CA

在目录 `ssl` 中执行

. 配置
+
[source,bash]
----
touch ca2.demo.com/index.txt
echo "01" > ca2.demo.com/serial
----
+
. 修改 `openssl.cnf`，修改所有的 `ca1.demo.com`, 和 `CA_default` 段的 `x509_extensions`：
+
[source,diff]
----
 [ CA_default ]
 
-dir            = ./ca1.demo.com                # Where everything is kept
+dir            = ./ca2.demo.com                # Where everything is kept
 
-x509_extensions        = v3_ca                 # The extensions to add to the cert
+x509_extensions        = usr_cert              # The extensions to add to the cert
 
-dir            = ./ca1.demo.com                # TSA root directory
+dir            = ./ca2.demo.com                # TSA root directory
----
+
. 生成私钥和证书请求
+
[source,bash]
----
openssl genrsa -out ca2.demo.com/private/cakey.pem 2048
openssl req -config openssl.cnf \
  -new -key ca2.demo.com/private/cakey.pem \
  -out ca2.demo.com/ca.csr
----

==== 二级 CA 签名

通过根 CA 对二级 CA 证书请求进行签名，在目录 `ca_1` 中执行

[source,bash]
----
openssl ca -config openssl.cnf -in ../ca2.demo.com/ca2.csr -out ../ca2.demo.com/ca2cert.pem
----

=== 客户端

在目录 `client` 中执行

[source,bash]
----
cp /etc/ssl/openssl.cnf .
openssl genrsa -out client.key 2048
openssl req -config openssl.cnf -new -key client.key -out client.csr
----

==== 客户端签名

在目录 `ca_2` 中执行

[source,bash]
----
openssl ca -config openssl.cnf \
  -in ../client/client.csr -out ../client/client.crt 
----

== 多域名证书

修改 `openssl.conf`
.openssl.conf
[source,conf]
----
subjectAltName=DNS:example.com,DNS:*.example.com
----
* 证书可对 example.com 和 example.com 二级域名生效

== 配置 Nginx

[source,nginx]
----
server {
  listen       443 ssl http2;
  listen       [::]:443 ssl http2;
  server_name  client.example.com;

  ssl_certificate client.crt;
  ssl_certificate_key client.key;
  # ...
}
----

配置多级证书时，需要将中间证书也添加到 `client.crt`，该文件包含两个证书：ca_2 和 client。也就是将 `ca_2/demoCA/cacert.pem` 和 `client/client.crt` 两个文件中的 `-----BEGIN CERTIFICATE-----` 和 `-----END CERTIFICATE-----` 部分放到同一个文件。根证书是可选的。

测试证书有效性

[source,bash]
----
openssl s_client -connect client.example.com:443
----

== 添加 CA 到 Linux 系统

* 直接通过 HTTPS 请求获取证书

[source,bash]
----
# 执行命令后，输入 quit
openssl s_client -showcerts -servername example.com -connect example.com:443 > example_com_0.pem

openssl x509 -inform PEM -in example_com_0.pem -text -out example_com.pem
----

* fedora 35

[source,bash]
----
sudo cp demoCA/cacert.pem /usr/share/pki/ca-trust-source/anchors/example_com.pem
sudo update-ca-trust
----

* Ubuntu 20.04

[source,bash]
----
sudo cp demoCA/cacert.pem /usr/local/share/ca-certificates/example_com.crt
sudo update-ca-certificates
----

* curl、Firefox 可生效, 但 Chrome 依旧有警告

[source,bash]
----
curl -v -I https://example.com
----

== 参考

* https://docs.azure.cn/zh-cn/articles/azure-operations-guide/application-gateway/aog-application-gateway-howto-create-self-signed-cert-via-openssl
* https://nginx.org/en/docs/http/configuring_https_servers.html
* https://docs.fedoraproject.org/en-US/quick-docs/using-shared-system-certificates/
* https://www.postgresql.org/docs/current/ssl-tcp.html
* https://www.linode.com/docs/guides/using-openssls-subjectaltname-with-multiple-site-domains/
* https://curl.se/docs/sslcerts.html
