= Ubuntu 22.04 系统安装记录
notfound <notfound@notfound.cn>
2.0, 2021-10-14: 更新于 2023-04-02
:sectanchors:

:page-slug: linux-install-ubuntu
:page-category: linux

安装时选择语言为英文，以创建英文目录。

== 卸载

[source,bash]
----
sudo apt purge --autoremove apport
sudo apt purge --autoremove avahi-daemon
----
* `apport` 错误收集程序
* `avahi-daemon` 造成过网络异常，用处也不大，卸载

== 安装

[source,bash]
----
sudo apt install gnome-shell-extensions
sudo apt install gnome-tweaks
sudo apt install terminator
----
* `gnome-shell-extensions` gnome 扩展管理工具
* `gnome-tweaks` 可调整字体缩放，曲线解决高分辨率缩放字体模糊
* `terminator` 可分屏终端

参考 https://www.fosslinux.com/44375/install-gnome-tweak-tool-ubuntu.htm

=== Gnome 插件

* 主题插件 https://extensions.gnome.org/extension/19/user-themes/
* 自动隐藏顶部栏 https://extensions.gnome.org/extension/545/hide-top-bar
* 通知弹窗右侧 https://extensions.gnome.org/extension/4105/notification-banner-position/
* 网速显示 https://extensions.gnome.org/extension/4308/network-stats/

=== 关闭动画

[source,bash]
----
gsettings set org.gnome.desktop.interface enable-animations false
----

== Wayland

Wayland 不稳定，当前不建议开启

=== Chrome 开启 wayland

编辑:

./usr/share/applications/google-chrome.desktop
[source,conf]
----
Exec=/usr/bin/google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland %U
----
* 添加 `--enable-features=UseOzonePlatform` 和 `--ozone-platform=wayland` 可解决浏览器字体模糊

参考 https://pychao.com/2021/01/04/using-google-chrome-chromium-with-native-wayland-backend-in-arch-linux/

=== Edge 开启 wayland

编辑:

./usr/share/applications/microsoft-edge.desktop
[source,conf]
----
Exec=/usr/bin/microsoft-edge-stable --ozone-platform=wayland --enable-features=UseOzonePlatform %U
----
* 添加 `--enable-features=UseOzonePlatform` 和 `--ozone-platform=wayland` 可解决浏览器字体模糊

=== VSCode 开启 wayland

编辑:

./usr/share/applications/code.desktop
[source,conf]
----
Exec=/usr/share/code/code --ozone-platform=wayland --enable-features=UseOzonePlatform --unity-launch %F
----
* 添加 `--enable-features=UseOzonePlatform` 和 `--ozone-platform=wayland` 可解决浏览器字体模糊

== 登陆窗口分辨率

将当前用户配置复制到 gdm 用户目录:

[source,bash]
----
sudo cp ~/.config/monitors.xml ~gdm/.config/monitors.xml
sudo chown gdm:gdm ~gdm/.config/monitors.xml
----

编辑 `/etc/gdm3/custom.conf`:

[source,toml]
----
WaylandEnable=false
----

* 关闭了 wayland 和上一条冲突

参考 https://albertomatus.com/changing-login-display-in-ubuntu-20-04/

== Git & Vim

安装：

[source,bash]
----
sudo apt install git vim
----

配置 Git：

[source,bash]
----
git config --global user.name $NAME
git config --global user.email $EMAIL

git config --global credential.helper cache
git config --global core.editor vim
git config --global core.quotepath false
git config --global diff.tool vimdiff
git config --global difftool.prompt no
git config --global grep.lineNumber true
----

== oh-my-zsh

[source,bash]
----
sudo apt install zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
----

编辑 `~/.zshrc` ，添加 `git` `emacs` `docker` `kubectl` 等。

== Emacs & Spacemacs

=== 安装 Emacs

通过 ppa 下载 Emacs 最新版，下载速度太慢，所以启用代理：

[source,bash]
----
sudo add-apt-repository ppa:kelleyk/emacs
sudo apt install emacs27
----

=== 安装配置 Spacemacs

使用 Spacemacs develop 分支：

[source,bash]
----
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
----

使用 spacemacs 自定义配置，然后拉取 org 文档：

设置图标和环境变量(解决输入法切换)：

[source,bash]
----
sudo vim /usr/share/applications/emacs27.desktop

Icon=/home/notfound/.emacs.d/core/banners/img/spacemacs.png
Exec=env LC_ALL=zh_CN.UTF-8 emacs %F
----

gtags 跳转：

[source,bash]
----
sudo apt install global
sudo apt install exuberant-ctags python-pygments
gunzip /usr/share/doc/global/examples/gtags.conf.gz -c > ~/.globalrc
echo "export GTAGSLABEL=ctags" >> ~/.zshrc
----

ag 搜索：

[source,bash]
----
sudo apt install silversearcher-ag
----

Hugo 安装 https://github.com/gohugoio/hugo/releases

[source,bash]
----
wget https://github.com/gohugoio/hugo/releases/download/v0.89.2/hugo_extended_0.89.2_Linux-64bit.deb
sudo dpkg -i hugo_extended_0.89.2_Linux-64bit.deb
----

== 语言

通过图形界面设置语言为中文。

中文字体：

[source,bash]
----
sudo apt install fonts-wqy-microhei fonts-wqy-zenhei
----

emoji：

[source,bash]
----
sudo apt install fonts-noto-color-emoji
----

== 修改 DNS

[source,bash]
----
sudo vim /etc/systemd/resolved.conf
sudo systemctl restart systemd-resolved.service
resolvectl dns
----

== 关闭图形界面

[source,bash]
----
# 获取默认启动
sudo systemctl get-default
# 开机不启动图形界面
sudo systemctl set-default multi-user.target
# 开机启动图形界面
sudo systemctl set-default graphical.target
----

https://linuxconfig.org/how-to-disable-enable-gui-on-boot-in-ubuntu-20-04-focal-fossa-linux-desktop[参考]

== 其他

* `google-chrome` https://dl.google.com/linux/direct/google-chrome-stable%5Fcurrent%5Famd64.deb[下载]
* `htop` 升级版 top
* `nginx`
* `openssh-server`
* `tree` 遍历目录下所有文件
* `nodejs` 参考 https://github.com/nodesource/distributions/blob/master/README.md[安装 NodeJS]
* `docker` 参考 https://docs.docker.com/install/linux/docker-ce/ubuntu/[安装 Docker]
* `flameshot` 截图工具，参考 https://linux.cn/article-10070-1.html[在 Linux 下截屏并编辑的最佳工具]
