= 使用 OpenSSL 生成 Nginx 证书
notfound <notfound@notfound.cn>
2.0, 2021-11-21: 创建
:sectanchors:

:page-slug: linux-ssl-nginx
:page-category: linux
:page-tags: nginx,ssl

系统环境：Ubuntu 22.04

== 方法 1：自签名证书

生成服务器私钥：

[source,bash]
----
openssl genrsa -out example.com.key 2048
----

生成证书签名请求：

[source,bash]
----
openssl req -new -key example.com.key -out example.com.csr
----
* `Common Name (eg, your name or your server's hostname)` 填写域名 `example.com`

使用证书签名请求以及私钥签发证书：

[source,bash]
----
openssl x509 -req -days 365 -in example.com.csr -signkey example.com.key -out example.com.crt
----

== 方法 2：生成自签名 CA 证书

=== CA

测试域名为 `example.com`

创建 CA 目录：

[source,bash]
----
mkdir -p ssl/demoCA/{certs,newcerts,crl,private}
cd ssl
touch demoCA/index.txt
echo "01" > demoCA/serial
cp /etc/ssl/openssl.cnf .
----

* CA 目录从 `/etc/pki/CA` 改为 `demoCA`

生成 CA 私钥和证书：

[source,bash]
----
openssl req -new -x509 -days 365 -newkey rsa:2048 \
  -keyout demoCA/private/cakey.pem \
  -out demoCA/cacert.pem \
  -config openssl.cnf
----
* 证书有效期 356 天
* 输出目录与配置文件一致
* 注意输入域名 `Common Name (eg, your name or your server's hostname) []:example.com`

查看 key 和证书：

[source,bash]
----
# 查看 rsa 私钥
openssl rsa -noout -text -in demoCA/private/cakey.pem
# 查看证书
openssl x509 -noout -text -in demoCA/cacert.pem
# 移除私钥密码
openssl rsa -in demoCA/cacert.pem -out demoCA/cacert.key
----

目录结构：

[source,text]
----
ssl
├── demoCA
│   ├── cacert.pem
│   ├── certs
│   ├── crl
│   ├── index.txt
│   ├── newcerts
│   ├── private
│   │   └── cakey.pem
│   └── serial
└── openssl.cnf
----

=== 客户端

生成客户端私钥：

[source,bash]
----
openssl genrsa -out example.com.key 2048
----

生成证书签名请求：

[source,bash]
----
openssl req -new -key example.com.key -out example.com.csr -config openssl.cnf
----
* 注意输入域名 `Common Name (eg, your name or your server's hostname) []: example.com`

使用 CA 根证书签发客户端证书：

[source,bash]
----
openssl ca -in example_com.csr -out example_com.crt -config openssl.cnf
----

== 方法 3：多级证书

创建目录：

[source,bash]
----
mkdir -p ssl/{ca1.demo.com,ca2.demo.com}/{certs,newcerts,crl,private}
cd ssl
----

目录结构：

[source,text]
----
ssl
├── ca1.demo.com
│   ├── certs
│   ├── crl
│   ├── newcerts
│   └── private
└── ca2.demo.com
    ├── certs
    ├── crl
    ├── newcerts
    └── private
----

=== 根 CA

配置：

[source,bash]
----
touch ca1.demo.com/index.txt
echo "01" > ca1.demo.com/serial

cp /etc/ssl/openssl.cnf .
----

修改 `openssl.cnf`，修改所有的 `demoCA`, 和 `CA_default` 域的 `x509_extensions`：

[source,diff]
----
 [ CA_default ]
 ... 
-dir            = ./demoCA              # Where everything is kept
+dir            = ./ca1.demo.com        # Where everything is kept
 ... 
-x509_extensions        = usr_cert      # The extensions to add to the cert
+x509_extensions        = v3_ca         # The extensions to add to the cert
 ... 
-dir            = ./demoCA              # TSA root directory
+dir            = ./ca1.demo.com        # TSA root directory
----

修改 `req_distinguished_name` 段如 `countryName_default` 等默认值避免反复填写相关信息：

[source,diff]
----
 [ req_distinguished_name ]
 countryName                    = Country Name (2 letter code)
-countryName_default            = AU
+countryName_default            = CN
 
 stateOrProvinceName            = State or Province Name (full name)
-stateOrProvinceName_default    = Some-State
+stateOrProvinceName_default    = GuangDong
 
 localityName                   = Locality Name (eg, city)
+localityName_default           = ShenZhen
 
 0.organizationName             = Organization Name (eg, company)
-0.organizationName_default     = Internet Widgits Pty Ltd
+0.organizationName_default     = demo
----

生成私钥和证书：

[source,bash]
----
openssl req -config openssl.cnf \
  -new -x509 -newkey rsa:2048 \
  -keyout ca1.demo.com/private/cakey.pem \
  -out ca1.demo.com/cacert.pem
----

=== 二级 CA

配置：

[source,bash]
----
touch ca2.demo.com/index.txt
echo "01" > ca2.demo.com/serial
----

生成私钥和证书请求：

[source,bash]
----
openssl genrsa -out ca2.demo.com/private/cakey.pem 2048
openssl req -config openssl.cnf \
  -new -key ca2.demo.com/private/cakey.pem \
  -out ca2.demo.com/ca.csr
----

通过根 CA 对二级 CA 证书请求进行签名：

[source,bash]
----
openssl ca -config openssl.cnf -in ca2.demo.com/ca.csr -out ca2.demo.com/cacert.pem
----

修改 `openssl.cnf`，替换全部 `ca1.demo.com` 和 `CA_default` 段的 `x509_extensions`，后续操作使用 `ca2.demo.com`：

[source,diff]
----
 [ CA_default ]
 ...
-dir            = ./ca1.demo.com                # Where everything is kept
+dir            = ./ca2.demo.com                # Where everything is kept
 ...
-x509_extensions        = v3_ca                 # The extensions to add to the cert
+x509_extensions        = usr_cert              # The extensions to add to the cert
 ...
-dir            = ./ca1.demo.com                # TSA root directory
+dir            = ./ca2.demo.com                # TSA root directory
----

=== 客户端

[source,bash]
----
export domain=demo.com
mkdir $domain
openssl genrsa -out $domain/$domain.key 2048
openssl req -config openssl.cnf -new -key $domain/$domain.key -out $domain/$domain.csr
----

客户端签名：

[source,bash]
----
openssl ca -config openssl.cnf \
  -in $domain/$domain.csr \
  -out $domain/$domain.crt
----

=== 多域名证书

修改 `openssl.conf`：

[source,diff]
----
 [ usr_cert ]
 ...
-# subjectAltName=email:copy
+subjectAltName=DNS:demo.io,DNS:*.demo.io
----
* 证书可对 demo.io 和 demo.io 二级域名生效

之后执行证书生成操作。

=== 问题

* 报错 curl: (60) SSL certificate problem: unable to get local issuer certificate
+
自签名证书无法通过网络获取证书链，因此在配置 Nginx 时，需要将证书链上除根证书以外的所有证书放到同一个证书文件。
+
这里需要将 `demo.com/demo.com.crt` 和 `ca2.demo.com/cacert.pem` 放到一起：
+
[source,bash]
----
# 合并两个文件内容
cat demo.com/demo.com.crt ca2.demo.com/cacert.pem > demo.com.crt
----

== 配置 Nginx

[source,nginx]
----
server {
  listen       443 ssl http2;
  listen       [::]:443 ssl http2;
  server_name  demo.com;

  ssl_certificate demo.com.crt;
  ssl_certificate_key demo.com.key;
  # ...
}
----

配置多级证书时，需要将中间证书也添加到证书文件，在这里需要将 `demo.com/demo.com.crt`、`ca2.demo.com/cacert.pem` 两个文件中的 `-----BEGIN CERTIFICATE-----` 和 `-----END CERTIFICATE-----` 部分放到同一个文件，根证书可选。

测试证书有效性：

[source,bash]
----
openssl s_client -connect client.example.com:443
----

== 添加 CA 到 Linux 系统

可直接通过 HTTPS 请求获取证书：

[source,bash]
----
# 执行命令后，输入 quit
openssl s_client -showcerts -servername example.com -connect example.com:443 > example_com_0.pem

openssl x509 -inform PEM -in example_com_0.pem -text -out example_com.pem
----

添加 CA 根证书：

[source,bash]
----
# fedora 35
sudo cp demoCA/cacert.pem /usr/share/pki/ca-trust-source/anchors/example.com.pem
sudo update-ca-trust

# Ubuntu 22.04
sudo cp demoCA/cacert.pem /usr/local/share/ca-certificates/example.com.crt
sudo update-ca-certificates
----

使用 curl 命令时，CA 证书会生效：

[source,bash]
----
curl -v -I https://example.com
----

=== Linux 浏览器

在 Linux上，Chromium (Chrome Edge) 使用 NSS 共享数据库，需要安装：

[source,bash]
----
sudo apt install libnss3-tools
----

[source,bash]
----
# 列出所有证书
certutil -d sql:$HOME/.pki/nssdb -L
# 列出证书的详细信息
certutil -d sql:$HOME/.pki/nssdb -L -n <certificate nickname>
# 添加 CA 根证书
certutil -d sql:$HOME/.pki/nssdb -A -t "C,," -n "ca1.demo.com" -i ca1.demo.com/cacert.pem
# 添加 CA 中间证书
certutil -d sql:$HOME/.pki/nssdb -A -t ",,"  -n "ca2.demo.com" -i ca2.demo.com/cacert.pem
# 删除 CA 证书
certutil -d sql:$HOME/.pki/nssdb -D -n "ca2.demo.com"
----


== 参考

* https://docs.azure.cn/zh-cn/articles/azure-operations-guide/application-gateway/aog-application-gateway-howto-create-self-signed-cert-via-openssl
* https://nginx.org/en/docs/http/configuring_https_servers.html
* https://docs.fedoraproject.org/en-US/quick-docs/using-shared-system-certificates/
* https://www.postgresql.org/docs/current/ssl-tcp.html
* https://www.linode.com/docs/guides/using-openssls-subjectaltname-with-multiple-site-domains/
* https://curl.se/docs/sslcerts.html
* https://chromium.googlesource.com/chromium/src/+/master/docs/linux/cert_management.md
