= Linux 环境使用 iostat 分析存储设备 IO
notfound <notfound@notfound.cn>
1.0, 2022-07-10: init
:sectanchors:

:page-slug: linux-cmd-iostat
:page-category: linux
:page-tags: shell,benchmark

系统环境 Ubuntu 20.04

`iostat` 可以获取 CPU 和 IO 设备统计信息，这里我们只关注 IO。

== iostat

[source,bash]
----
iostat -dx
----

* `-d` 显示设备利用率报告
* `-x` 显示扩展的统计信息

输出结果如下：

[source,text]
----
Device            r/s     rkB/s   rrqm/s  %rrqm r_await rareq-sz     w/s     wkB/s   wrqm/s  %wrqm w_await wareq-sz     d/s     dkB/s   drqm/s  %drqm d_await dareq-sz     f/s f_await  aqu-sz  %util
nvme0n1         29.06    925.15    13.46  31.66    0.23    31.83   44.07   2957.49    60.43  57.83    3.29    67.11    0.00      0.00     0.00   0.00    0.00     0.00   10.05    0.17    0.15   3.52
----

* `Device` 设备
* `r/s` 设备每秒完成的读取请求数（合并后）。
* `w/s` 设备每秒完成的写入请求数（合并后）。
* `d/s` 设备每秒完成的丢弃请求数（合并后）。
* `f/s` 设备每秒完成的刷新请求数（合并后）。这会计算磁盘执行的刷新请求。不跟踪分区的刷新请求。在被合并之前，刷新操作被算作写入
* `rsec/s (rkB/s, rMB/s)` 每秒从设备读取的扇区数（千字节、兆字节）。
* `wsec/s (wkB/s, wMB/s)` 每秒写入设备的扇区数（千字节、兆字节）。
* `dsec/s (dkB/s, dMB/s)` 每秒为设备丢弃的扇区数（千字节、兆字节）。
* `rrqm/s` 每秒合并的排队到设备的读取请求数。
* `wrqm/s` 每秒合并并排队到设备的写入请求数。
* `drqm/s` 每秒合并的排队到设备的丢弃请求数。
* `%rrqm` 在发送到设备之前合并在一起的读取请求的百分比。
* `%wrqm` 写入请求在发送到设备之前合并在一起的百分比。
* `%drqm` 在发送到设备之前合并在一起的丢弃请求的百分比。
* `rareq-sz` 向设备发出的读取请求的平均大小（以千字节为单位）。
* `wareq-sz` 向设备发出的写入请求的平均大小（以千字节为单位）。
* `dareq-sz` 向设备发出的丢弃请求的平均大小（以千字节为单位）。
* `r_await` 向要服务的设备发出读取请求的平均时间（以毫秒为单位）。 这包括队列中的请求所花费的时间以及为它们提供服务所花费的时间。
* `w_await` 向要服务的设备发出的写入请求的平均时间（以毫秒为单位）。 这包括队列中的请求所花费的时间以及为它们提供服务所花费的时间。
* `d_await` 向要服务的设备发出丢弃请求的平均时间（以毫秒为单位）。 这包括队列中的请求所花费的时间以及为它们提供服务所花费的时间。
* `f_await` 向要服务的设备发出刷新请求的平均时间（以毫秒为单位）。 块层结合刷新请求，一次最多执行一个。 因此刷新操作的时间可能是原来的两倍：等待当前的刷新请求，然后执行它，然后等待下一个。
* `aqu-sz` 向设备发出的请求的平均队列长度。 注意：在以前的版本中，此字段称为 avgqu-sz。
* `%util` 向设备发出 I/O 请求的已用时间百分比（设备的带宽利用率）。对于串行服务请求的设备，当该值接近 100% 时，会发生设备饱和。但是对于并行处理请求的设备，例如 RAID 阵列和现代 SSD，这个数字并不能反映它们的性能限制。

== gnuplot 画图

=== 数据

通过 iostat 生成数据

[source,bash]
----
iostat -dx 1 10 | grep nvme0n1 > iostat.txt
----
* 每 1 秒采集一次数据，采集 10 次
* 仅显示设备 nvme0n1 这一行 

=== 画图

.iostat.gnuplot
[source,gnuplot]
----
# set terminal qt persist
set terminal svg  # <1>
set output 'iostat.svg' # <2>

set title 'iostat -dx 1 10'

set xlabel "时间 (秒)"
set ylabel "操作次数"
set y2label "百分比" # <3>
set ytics nomirror # <4>
set y2tics # <5>
set y2range [0:14] # <6>
set grid # <7>
# <8>
plot \
         'iostat.txt' using  2 with lines linewidth 2 axis x1y1 title 'r/s', \
         'iostat.txt' using  8 with lines linewidth 2 axis x1y1 title 'w/s', \
         'iostat.txt' using 23 with lines linewidth 2 axis x1y2 title '%util'
----
<1> 生成 SVG
<2> 输出文件名
<3> 设置 y2 （第二坐标轴）标签
<4> 不使用 y1 刻度镜像
<5> 添加 y2 刻度标记
<6> 设置 y2 范围
<7> 设置网格
<8> 使用 2、8、23 列划线图

之后，执行命令：

[source,bash]
----
gnuplot iostat.gnuplot
----

生成图片：

image::/images/iostat.svg[iostat]

== 测试
.test.sh
[source,bash]
----
#!/bin/bash

ulimit -n 16400

args='--threads=1 --time=30 --file-num=1024 --file-total-size=1G --file-test-mode=rndrw'
devise=/dev/sdb4
options="relatime noatime"
output=$PWD

devise_name=$(basename $devise)

set -x
for option in $options
do
    if [ $option = "noatime" ]; then
        sudo mount -o rw,noatime $devise /mnt/hdd
        echo "noatime"
    elif [ $option = "relatime" ]; then
        sudo mount $devise /mnt/hdd
        echo "relatime"
    else
        exit -1
    fi

    findmnt /mnt/hdd > $output/$option.txt
    cd /mnt/hdd/tmp/sysbench

    sysbench fileio $args prepare > $output/$option.prepare.txt

    sleep 10

    iostat -dx 1 $devise | grep --line-buffered $devise_name > $output/$option.run.iostat.txt &
    systemd-run --user --scope -p MemoryMax=128M sysbench fileio $args run  > $output/$option.run.txt
    kill %%

    sysbench fileio $args cleanup > $output/$option.cleanup.txt

    cd -
    sudo umount /mnt/hdd
done

# https://askubuntu.com/questions/488324/redirect-an-output-to-a-file-from-command-piping-grep
# https://unix.stackexchange.com/questions/44985/limit-memory-usage-for-a-single-linux-process
----

.iostat.gnuplot
[source,gnuplot]
----
set terminal qt persist
set title 'iostat relatime and noatime'
set xlabel "时间 (秒)"
set ylabel "kB/s"
set y2label "百分比"
set ytics nomirror
set y2tics
set y2range [0:120]
set grid

plot \
         'relatime.run.iostat.txt' using  3 with lines linewidth 2 axis x1y1 title 'relatime rkB/s', \
         'relatime.run.iostat.txt' using  9 with lines linewidth 2 axis x1y1 title 'relatime wkB/s', \
         'relatime.run.iostat.txt' using 21 with lines linewidth 2 axis x1y2 title '%util', \
         'noatime.run.iostat.txt'  using  3 with lines linewidth 2 axis x1y1 title 'noatime rkB/s', \
         'noatime.run.iostat.txt'  using  9 with lines linewidth 2 axis x1y1 title 'noatime wkB/s', \
         'noatime.run.iostat.txt'  using 21 with lines linewidth 2 axis x1y2 title '%util'
----

== 参考

- man iostat
- https://book.douban.com/subject/23008813/[《 高性能MySQL(第3版) 》]
