= Linux nftables 基本使用
notfound <notfound@notfound.cn>
1.0, 2023-03-26: init

:page-slug: linux-nftables-start
:page-category: linux

* 操作系统: Ubuntu 22.04

`nftables` 框架对数据包进行分类，它是 `iptables`、`ip6tables`、`arptables`、`ebtables` 和 `ipset` 实用程序的后续者。

== 启动

nftables 通过 systemd 管理，配置文件路径 `/etc/nftables.conf`。

[source,bash]
----
# 查看 systemd 配置
systemctl cat nftables.service
# 查看服务状态
systemctl status nftables.service
# 启动服务
sudo systemctl start nftables.service
# 设置服务为开机启动
sudo systemctl enable nftables.service
----

`nftables` 支持 `nft` 命令和 `nftables` 脚本，默认配置文件 `/etc/nftables.conf` 就是一个可执行的 `nftables` 脚本：

./etc/nftables.conf
[source,nft]
----
#!/usr/sbin/nft -f

flush ruleset # <1>

table inet filter { # <2>
	chain input { # <3>
		type filter hook input priority 0; # <4>
	}
	chain forward {
		type filter hook forward priority 0;
	}
	chain output {
		type filter hook output priority 0;
	}
}
----
<1> 清空规则集
<2> 创建表
<3> 创建链

== Netfilter

https://www.netfilter.org/index.html[netfilter] 为 Linux 内核提供了包过滤功能，nftables 是 netfilter 的一部分。

.Netfilter hooks into Linux networking packet flows (https://wiki.nftables.org/wiki-nftables/index.php/Netfilter_hooks[图片来源])
image::/images/nf-hooks.svg[]

.address families
[Attributes]
|===
| 地址族 | 说明

| netdev | 匹配处理入口和出口的数据包
| inet   | 匹配 IPv4 和 IPv6 数据包
| ip     | 仅匹配 IPv4 数据包，默认值
| ip6    | 仅匹配 IPv6 数据包
| bridge | 匹配通过网桥设备的数据包
| arp    | 匹配 IPv4 地址解析协议(ARP)数据包
|===

.hook
[Attributes]
|===
| hook | 地址族 | 描述

| ingress
| ip/ip6/inet/netdev
| 所有进入系统的数据包都由这个钩子处理。它在第 3 层协议处理程序之前被调用，因此在 prerouting hook 之前被调用，并且它可以用于过滤和监管。Ingress 仅适用于 Inet 族（从 Linux 内核 5.10 起）。

| prerouting
| ip/ip6/inet
| 所有进入系统的数据包都由 prerouting hook 处理，在路由过程之前调用。

| input
| ip/ip6/inet/arp
| 传送到本地系统的数据包由 input hook 处理。

| output
| ip/ip6/inet/arp
| 本地进程发送的数据包由 output hook 处理。

| forward
| ip/ip6/inet
| 转发到不同主机的数据包由 forward hook 处理。

| postrouting
| ip/ip6/inet
| 离开系统的所有数据包都由 postrouting hook 处理。

| egress
| netdev
| 所有离开系统的数据包都由这个钩子处理。它在第 3 层协议处理程序之后和 tc engress 之前被调用。它可用于后期过滤和监管。

|===

== 操作

nftables 中的表是一个包含链、规则、集合和其他对象集合的名字空间。

=== 表

创建表的语法如下：

[source,nft]
----
table <table_address_family> <table_name> {
}
----

等同于命令行：

[source,bash]
----
nft add table <table_address_family> <table_name>
----
* `table_address_family` 以下值其中之一: `netdev`, `inet`, `ip`, `ip6`,  `bridge`, `arp`

删除表：

[source,bash]
----
nft delete table <table_address_family> <table_name>
----

=== 链

[source,nft]
----
chain <chain_name> {
  type <type> hook <hook> priority <priority>
}
----

等同于：

[source,bash]
----
nft add chain <table_address_family> <table_name> <chain_name> \
	{ type <type> hook <hook> priority <priority> \; policy <policy> \; }
----

参数说明：

.参数 <type>
[Attributes]
|===
| 类型 | 地址族 | Hooks | 描述

| filter
| arp, bridge, ip, ip6 and inet
| all
| 标准链类型

| nat
| ip, ip6, inet
| prerouting, input, output, postrouting               
| 这个类型的链根据连接跟踪条目执行原生地址转换。只有第一个数据包遍历此链类型。

| route
| ip, ip6
| output
| 如果 IP 标头的相关部分已更改，则遍历此链类型的数据包会导致新的路由查找

|===

.参数 <priority>
[Attributes]
|===
| 名称 | 值 | 地址族 | Hooks

| raw       | -300  | ip, ip6, inet              | all
| mangle    | -150  | ip, ip6, inet              | all
.2+| dstnat | -100  | ip, ip6, inet              | prerouting
            | -300  | bridge                     | prerouting
.2+| filter | 0     | ip, ip6, inet, arp, netdev | all
            | -200  | bridge                     | all
| security  | 50    | ip, ip6, inet              | all
.2+| srcnat | 100   | ip, ip6, inet              | postrouting
            | 300   | bridge                     | postrouting
| out       | 100   | bridge                     | output

|===

.参数 <policy>
|===
| policy | 说明

| accept
| 接受

| drop 
| 丢弃

|===

删除：

[source,bash]
----
nft delete chain <table_name> <chain_name>
----

=== 规则

添加:

[source,bash]
----
nft add rule <table_address_family> <table_name> <chain_name> <rule>
----

删除：

[source,bash]
----
# 查看 handle
nft --handle list chain <table_address_family> <table_name> <chain_name>
nft delete rule <table_address_family> <table_name> <chain_name> handle <handle>
----

== 示例

=== 备份和恢复

[source,bash]
----
# 显示 nftables 规则集
nft list ruleset
# 备份
nft list ruleset > file.nft
# 恢复
nft -f file.nft
# 清空
nft flush ruleset
----

=== 网络地址转换(NAT)

在 IP 数据包通过路由器或防火墙时重写来源 IP 地址或目的 IP 地址。

测试环境：

[Attributes]
|===
| interface | IPv4

| wlan0 | 192.168.0.3/24
| eth0 | 192.168.1.3/24

|===

需要开启 Linux 转发功能：

[source,bash]
----
# 检查 net.ipv4.ip_forward 是否为开启
sysctl -n net.ipv4.ip_forward
# 配置
sudo sysctl -w net.ipv4.ip_forward=1
----

或者修改文件 `/etc/sysctl.conf` 后执行 `sudo sysctl -p` 让配置生效：

./etc/sysctl.conf
[source,conf]
----
net.ipv4.ip_forward=1
----

=== Destination NAT(DNAT)

在 IP 数据包通过路由器或防火墙时重写目的 IP 地址。

[source,nft]
----
table ip nat {
	chain prerouting {
		type nat hook prerouting priority dstnat; policy accept;
		iif "wlan0" tcp dport { 8080 } dnat to 192.168.1.3
	}
}
----
* 这将从接口 wlan0 (`iif`: Input interface index) 进入且 TCP 目标端口 8080 的流量重定向到 192.168.1.3。

命令行方式：

[source,bash]
----
nft add table nat
nft 'add chain nat prerouting { type nat hook prerouting priority -100; }'
nft 'add rule nat prerouting iif wlan0 tcp dport { 80, 443, 8080 } dnat to 192.168.1.3'
----

==== 测试

[source,bash]
----
# 服务端
ruby -run -e httpd -- --bind-address=192.168.1.3 --port=8080 /tmp
----
* 启动 HTTP 服务并绑定 IP 192.168.1.3 和端口 8080

另一台主机做为客户端访问 http://192.168.0.3:8080 ，可正常访问到服务端

==== 问题

这里的目标设置为 `127.0.0.1` 不会生效，需要修改 (https://serverfault.com/questions/1021798/how-to-redirect-requests-on-port-80-to-localhost3000-using-nftables[参考])：


[source,bash]
----
sudo sysctl -w net.ipv4.conf.wlan0.route_localnet=1
----

=== Redirect(DNAT)

将 IP 数据包重定向到本机的另一个端口，重定向是 DNAT 的特例。

[source,nft]
----
table ip nat {
	chain prerouting {
		type nat hook prerouting priority dstnat; policy accept;
		tcp dport 8081 redirect to :8080
	}
}
----

命令行方式：

[source,bash]
----
nft add table nat
nft 'add chain nat prerouting { type nat hook prerouting priority -100; }'
nft add rule nat prerouting tcp dport 8081 redirect to 8080
----

==== 测试

[source,bash]
----
ruby -run -e httpd -- --bind-address=192.168.0.3 --port=8080 /tmp
----
* 启动 HTTP 服务并绑定 IP 192.168.0.3 和端口 8080

另一台主机做为客户端访问 http://192.168.0.3:8081 ，可正常访问到服务端

=== 限制 ping 请求速率

[source,nft]
----
table ip filter {
	chain input {
		type filter hook input priority filter; policy accept;
		icmp type echo-request limit rate 10/second accept #<1>
		icmp type echo-request limit rate over 10/second drop #<2>
	}
}
----
<1> 此规则与低于10/秒速率的数据包匹配，接受；
<2> 此规则与高于10/秒速率的数据包匹配，丢弃。

命令行方式：

[source,bash]
----
nft add table filter
nft 'add chain filter input { type filter hook input priority 0; }'
nft add rule filter input icmp type echo-request limit rate 10/second accept
nft add rule filter input icmp type echo-request limit rate over 10/second drop
----

可在相同主机测试：

[source,bash]
----
# 并发执行多条
ping 192.168.1.3 -i 0.2
----
* 每 0.2 秒发送一条请求，请求频率过高，会存在丢包

=== 限制数据传输速率

[source,nft]
----
table ip filter {
	chain input {
		type filter hook input priority filter; policy accept;
		limit rate 1 mbytes/second accept # <1>
		limit rate over 1 mbytes/second drop # <2>
	}
}
----
<1> 此规则与低于 1 mbytes/秒速率的数据包匹配，接受；
<2> 此规则与高于 1 mbytes/秒速率的数据包匹配，丢弃。

命令行方式：

[source,bash]
----
nft add table filter
nft 'add chain filter input { type filter hook input priority 0; }'
nft add rule filter input limit rate 1 mbytes/second accept
nft add rule filter input limit rate over 1 mbytes/second drop
----

=== 限制连接数

限制连接数需要使用 `ct` (connection tracking, conntrack)。

[source,nft]
----
table ip filter {
	chain input {
		type filter hook input priority filter; policy accept;
		tcp dport 22 ct count 3 accept # <1>
		tcp dport 22 ct count over 3 reject # <2>
	}
}
----
<1> 此规则与低于 3 个连接的数据包匹配，接受；
<2> 此规则与高于 3 个连接的数据包匹配，拒绝。

命令行方式：

[source,bash]
----
nft add table filter
nft 'add chain filter input { type filter hook input priority 0; policy accept; }'
nft add rule filter input tcp dport 22 ct count 3 accept
nft add rule filter input tcp dport 22 ct count over 3 reject
----

* 连接超出限制时，会出现卡顿的现象。
* 连接状态会保存一段时间。

=== 禁止容器访问内网

容器的网桥为 `docker0`，通过控制 `docker0` 可控制容器的网络。

[source,nft]
----
table ip filter {
	chain DOCKER-USER {
		iifname "docker0" ip daddr 192.168.0.4 accept # <1>
		iifname "docker0" ip daddr 192.168.0.0/24 drop # <2>
	}
}
----
<1> 匹配输入的接口名称(`iifname`: Input interface name)为 `docker 0` 且目标地址 `192.168.0.4`，接受；
<2> 匹配输入的接口名称(`iifname`: Input interface name)为 `docker 0` 且目标地址 `192.168.0.4/24`，丢弃。

命令行方式：

[source,bash]
----
nft 'add rule filter DOCKER-USER iifname "docker0" ip daddr 192.168.0.4 accept'
nft 'add rule filter DOCKER-USER iifname "docker0" ip daddr 192.168.0.0/24 drop'
----

==== 测试

[source,bash]
----
docker run -d -i -t ubuntu:22.04 bash
apt update
apt install iputils-ping

# 容器宿主机，通
ping 192.168.0.3
# accept, 通
ping 192.168.0.4
# drop, 不通
ping 192.168.0.5
----

=== 外部请求转发到容器

通过修改目标 IP 地址，将发送给宿主机请求转发到容器内。

[source,nft]
----
table ip nat {
	chain DOCKER {
		iifname != "docker0" tcp dport 9090 dnat to 172.17.0.2:9090 # <1>
	}
}
----
<1> 匹配输入接口名称(Input interface name)不为 `docker0` 且目标端口为 `9090` 的请求，转发到容器内。

命令行方式：

[source,bash]
----
nft 'add rule ip nat DOCKER iifname != "docker0" tcp dport 9090 dnat to 172.17.0.2:9090'
----

==== 测试

[source,bash]
----
docker run -d -i -t ubuntu:22.04 bash
apt update
apt install ruby
ruby -run -e httpd -- --bind-address=0.0.0.0 --port=9090 /tmp

# 容器宿主机，通
curl http://192.168.0.3:9090
# 其他机器，通
curl http://192.168.0.3:9090
----

== 参考

* man nft
* https://access.redhat.com/docnft 'add rule ip nat DOCKER iifname != "docker0" meta l4proto tcp tcp dport 9090 dnat to 172.17.0.2:9090'
umentation/zh-cn/red_hat_enterprise_linux/9/html/configuring_firewalls_and_packet_filters/getting-started-with-nftables_firewall-packet-filters
* https://wiki.archlinuxcn.org/zh-hans/Nftables
* https://jensd.be/1086/linux/forward-a-tcp-port-to-another-ip-or-port-using-nat-with-nftables
* https://wiki.nftables.org/wiki-nftables/index.php/Main_Page
* https://docs.docker.com/network/iptables/
* https://arthurchiao.art/blog/deep-dive-into-iptables-and-netfilter-arch-zh/
* https://arthurchiao.art/blog/conntrack-design-and-implementation-zh/
