= CoreDNS 安装和使用
notfound <notfound@notfound.cn>
1.0, 2023-03-28: init

:page-slug: linux-coredns
:page-category: cloud-native
:page-tags: dns

== 安装和启动

下载并安装：

[source,bash]
----
COREDNS_VERSION=1.10.1
wget "https://github.com/coredns/coredns/releases/download/v${COREDNS_VERSION}/coredns_${COREDNS_VERSION}_linux_amd64.tgz"
sudo tar -C /usr/bin -xzvf "coredns_${COREDNS_VERSION}_linux_amd64.tgz"
----

创建用户和目录：

[source,bash]
----
sudo useradd --home-dir /var/lib/coredns --shell /usr/sbin/nologin --no-create-home --user-group coredns
sudo mkdir /var/lib/coredns
sudo chown coredns:coredns /var/lib/coredns

sudo mkdir /etc/coredns
----

coredns 配置文件：

./etc/coredns/Corefile
[source,corefile]
----
.:1053 {
	forward . 119.29.29.29
}
----
* 监听端口 `1053`

systemd 配置：

./lib/systemd/system/coredns.service
[source,systemd]
----
[Unit]
Description=CoreDNS DNS server
Documentation=https://coredns.io
After=network.target

[Service]
PermissionsStartOnly=true
LimitNOFILE=1048576
LimitNPROC=512
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
User=coredns
WorkingDirectory=~
ExecStart=/usr/bin/coredns -conf=/etc/coredns/Corefile
ExecReload=/bin/kill -SIGUSR1 $MAINPID
Restart=on-failure

[Install]
WantedBy=multi-user.target
----
* `CAP_NET_BIND_SERVICE` 非 root 用户可绑定 1024 以下端口，参考 `man capabilities`；
* `CapabilityBoundingSet` 能力边界，表示限制；
* `AmbientCapabilities` 能力授予。

启动：

[source,bash]
----
sudo systemctl start coredns.service
# 开机启动
sudo systemctl enable coredns.service
----

查看日志：

[source,bash]
----
journalctl --follow --unit=coredns.service
----

测试：

[source,bash]
----
dig @localhost -p 1053 google.com A
dig @localhost -p 1053 ipv6.google.com AAAA
----
* `@server` 查询使用的 IP 或者 hostname
* `-p` 查询使用的端口
* `A` 查询 IPv4 地址
* `AAAA` 查询 IPv6 地址

== 配置

配置解析域名 `demo.io`：

./etc/coredns/Corefile
[source,corefile]
----
demo.io:1053 {
	file /etc/coredns/db.demo.io # <1>
	log
}

.:1053 {
	forward . 119.29.29.29
	log
	errors
	cache
}
----
* DNS zone 文件路径

创建 DNS zone 文件：

./etc/coredns/db.demo.io
[source,dns-zone]
----
$ORIGIN demo.io.#<1>
$TTL 8h#<2>
@       IN SOA ns1.demo.io. hostmaster.demo.io. (#<3>
                2023032901 ; serial
                7200       ; refresh (2 hours)
                3600       ; retry (1 hour)
                1209600    ; expire (2 weeks)
                3600       ; minimum (1 hour)
                )

        IN NS ns1.demo.io.#<4>
        IN NS ns2.demo.io.
        IN MX 10 mail.demo.io.#<5>

#<6>
www     IN A     127.0.0.1
        IN AAAA  ::1
ns1     IN A     127.0.0.1
        IN AAAA  ::1
ns2     IN A     127.0.0.1
        IN AAAA  ::1
mail    IN A     127.0.0.1
        IN AAAA  ::1
@       IN A     127.0.0.1
        IN AAAA  ::1
*       IN A     127.0.0.1
        IN AAAA  ::1
----
<1> 源，语法：
+
[source,text]
----
$ORIGIN <domain-name> [<comment>]
----
+
<2> TTL 默认生存时间；
+
<3> SOA 语法，多行时需要使用 `()`，`;` 可用来单行注释：
+
[source,text]
----
name class type mname rname serial refresh retry expire minimum
----
+
* `name` 区域名称，使用 `@` 时会被替换为 `$ORIGIN`；
* `class` 在 SOA 记录中，始终为 `IN`(Internet)；
* `type` 在 SOA 记录中，始终为 `SOA`；
* `mname` 此区域的主域名服务器主机名；
* `rname` 负责此区域的邮箱，将邮箱的 `@` 替换为 `.`；
* `serial` 区域文件的版本号，主服务器序列大时次域名服务器才会更新，通常的格式为 `<year><month><day><two-digit-number>`；
* `refresh` 次服务器刷新时间；
* `retry` 次服务器失败重试时间；
* `expire` 次服务器失败后，停止查询时间；
<4> 此区域的权威 DNS 服务器，区域需要至少一个域名服务器 (`NS`) 记录， 但 RFC 1912 要求两个。
<5> 邮件交换器 (`MX`)，数字为优先级，数字越小优先级越高
<6> 设置域名解析：
a. `A` IPv4 地址，`AAAA` IPv6 地址
b. `@` 直接解析主域名，`*` 泛解析二级域名

测试:

[source,bash]
----
host -p 1053 demo.io
# demo.io has address 127.0.0.1
# demo.io has IPv6 address ::1
# demo.io mail is handled by 10 mail.demo.io.
host -p 1053 app.demo.io
# app.demo.io has address 127.0.0.1
# app.demo.io has IPv6 address ::1
----

== 配置系统 DNS 解析

修改文件：

./etc/systemd/resolved.conf
[source,conf]
----
DNS=127.0.0.1:1053
----

重启：

[source,bash]
----
sudo systemctl restart systemd-resolved.service
----

== 参考

* man capabilities
* https://coredns.io/manual/toc/
* https://github.com/coredns/deployment/tree/master/systemd
* https://unix.stackexchange.com/questions/580597/what-is-the-difference-between-ambientcapabilities-and-capabilityboundingset
* https://www.cisco.com/c/zh_cn/support/docs/ip/domain-name-system-dns/12684-dns-resource.html
* https://access.redhat.com/documentation/zh-cn/red_hat_enterprise_linux/9/html/managing_networking_infrastructure_services/assembly_configuring-zones-on-a-bind-dns-server_assembly_setting-up-and-configuring-a-bind-dns-server
