= CoreDNS 安装和使用
notfound <notfound@notfound.cn>
1.0, 2023-03-28: init

:page-slug: linux-coredns
:page-category: cloud-native
:page-tags: dns

== 服务端

=== 安装

创建用户 coredns：

[source,bash]
----
sudo adduser \
    --system \
    --disabled-password \
    --disabled-login \
    --home /var/lib/coredns \
    --group \
    coredns
----
* 系统用户
* 禁用密码认证
* 禁止登录
* 主目录 `/var/lib/coredns`
* 添加组

下载并安装：

[source,bash]
----
COREDNS_VERSION=1.11.1
curl -o coredns.tgz -sSL "https://github.com/coredns/coredns/releases/download/v${COREDNS_VERSION}/coredns_${COREDNS_VERSION}_linux_amd64.tgz"
tar -xzvf coredns.tgz
sudo install -o root -g root -m 0755 coredns /usr/bin/coredns
----

=== Corefile

新建 coredns 配置文件：

./etc/coredns/Corefile
[source,corefile]
----
. {
    forward . 119.29.29.29
    log
}
----
* 监听端口 `53`，请求转发到指定 DNS
* 调试时可打开日志插件

=== systemd 配置

添加 systemd 配置文件：

./lib/systemd/system/coredns.service
[source,systemd]
----
[Unit]
Description=CoreDNS DNS server
Documentation=https://coredns.io
After=network.target

[Service]
PermissionsStartOnly=true
LimitNOFILE=1048576
LimitNPROC=512
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
User=coredns
WorkingDirectory=~
ExecStart=/usr/bin/coredns -conf=/etc/coredns/Corefile
ExecReload=/bin/kill -SIGUSR1 $MAINPID
Restart=on-failure

[Install]
WantedBy=multi-user.target
----
* `CAP_NET_BIND_SERVICE` 非 root 用户可绑定 1024 以下端口，参考 `man capabilities`；
* `CapabilityBoundingSet` 能力边界，表示限制；
* `AmbientCapabilities` 能力授予。

启动：

[source,bash]
----
sudo systemctl start coredns.service
# 开机启动
sudo systemctl enable coredns.service
----

查看日志：

[source,bash]
----
sudo journalctl --follow --unit=coredns.service
----

测试：

[source,bash]
----
dig @localhost google.com A
dig @localhost ipv6.google.com AAAA
----
* `@server` 查询使用的 IP 或者 hostname
* `A` 查询 IPv4 地址
* `AAAA` 查询 IPv6 地址

=== 添加域名解析

配置解析域名 `notfound.cn`：

./etc/coredns/Corefile
[source,corefile]
----
notfound.cn {
    file /etc/coredns/notfound.cn.zone
    log
}

. {
    forward . 119.29.29.29
    log
    cache
}
----
* `file` DNS zone 文件路径

创建 DNS zone 文件：

./etc/coredns/notfound.cn.zone
[source,dns-zone]
----
$ORIGIN notfound.cn.
$TTL 8h

; SOA record
@   3600 SOA sinew.dnspod.net. freednsadmin.dnspod.com. (
                2024062201  ; serial
                7200        ; refresh (2 hours)
                3600        ; retry (1 hour)
                1209600     ; expire (2 weeks)
                3600        ; minimum (1 hour)
                )

; NS records
@   86400   IN  NS  sinew.dnspod.net.
@   86400   IN  NS  rose.dnspod.net.

; MX records
@   600 IN  MX  10  mxbiz2.qq.com.
@   600 IN  MX  5   mxbiz1.qq.com.

www     IN A     127.0.0.1
        IN AAAA  ::1
@       IN A     192.168.0.254
*       IN A     192.168.0.254
----
. `ORIGIN` 源，语法：
+
[source,text]
----
$ORIGIN <domain-name> [<comment>]
----
+
. `TTL` 默认生存时间；
+
. SOA 语法，多行时需要使用 `()`，`;` 可用来单行注释：
+
[source,text]
----
name class type mname rname serial refresh retry expire minimum
----
+
* `name` 区域名称，使用 `@` 时会被替换为 `$ORIGIN`；
* `class` 在 SOA 记录中，始终为 `IN`(Internet)；
* `type` 在 SOA 记录中，始终为 `SOA`；
* `mname` 此区域的主域名服务器主机名；
* `rname` 负责此区域的邮箱，需要将邮箱的 `@` 替换为 `.`；
* `serial` 区域文件的版本号，主服务器序列大时次域名服务器才会更新，通常的格式为 `<year><month><day><two-digit-number>`；
* `refresh` 次服务器刷新时间；
* `retry` 次服务器失败重试时间；
* `expire` 次服务器失败后，停止查询时间；
. `NS` 此区域的权威 DNS 服务器，区域需要至少一个域名服务器 (`NS`) 记录， 但 RFC 1912 要求两个。
. `MX` 邮件交换器，数字为优先级，数字越小优先级越高
. 设置域名解析：
a. `A` IPv4 地址，`AAAA` IPv6 地址
b. `@` 直接解析主域名，`*` 泛解析二级域名

测试:

[source,bash]
----
host notfound.cn
# notfound.cn has address 192.168.0.254
# notfound.cn mail is handled by 10 mail.notfound.cn.

host www.notfound.cn
# www.notfound.cn has address 127.0.0.1
# www.notfound.cn has IPv6 address ::1
----

== 客户端

修改文件：

./etc/systemd/resolved.conf
[source,conf]
----
DNS=127.0.0.1
----

重启：

[source,bash]
----
sudo systemctl restart systemd-resolved.service
----

== 问题

gpg 添加失败：

[source,bash]
----
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E1DD270288B4E6030699E45FA1715D88E1DF1F24
gpg: keyserver receive failed: Server indicated a failure
----

诊断：

[source,bash]
----
dig +short keyserver.ubuntu.com
----

修改：

./etc/coredns/Corefile
[source,corefile]
----
. {
    bind 192.168.1.68
    header {
        response set ra aa
        response clear rd
    }
    forward . 119.29.29.29
    cache
}
----

参考： https://askubuntu.com/questions/291035/how-to-add-a-gpg-key-to-the-apt-sources-keyring

== 参考

* man capabilities
* https://coredns.io/manual/toc/
* https://github.com/coredns/deployment/tree/master/systemd
* https://unix.stackexchange.com/questions/580597/what-is-the-difference-between-ambientcapabilities-and-capabilityboundingset
* https://www.cisco.com/c/zh_cn/support/docs/ip/domain-name-system-dns/12684-dns-resource.html
* https://docs.redhat.com/zh_hans/documentation/red_hat_enterprise_linux/9/html/managing_networking_infrastructure_services/assembly_configuring-zones-on-a-bind-dns-server_assembly_setting-up-and-configuring-a-bind-dns-server
