= PostgreSQL 安装与使用
notfound <notfound@notfound.cn>
1.0, 2021-10-16: 创建
:sectanchors:

:page-slug: postgresql-install
:page-category: database
:page-tags: postgresql

* Ubuntu 22.04
* PostgreSQL 16

== 安装

安装 PostgreSQL：

[source,bash]
----
sudo sh -c 'echo "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get install postgresql
----
* 添加 Ubuntu 源、GPG KEY，然后安装最新版

安装 PgAdmin4：

[source,bash]
----
sudo sh -c 'echo "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list'
sudo curl https://www.pgadmin.org/static/packages_pgadmin_org.pub | sudo apt-key add
sudo apt-get update
sudo apt install pgadmin4
----
* 添加 Ubuntu 源、GPG KEY，然后安装最新版

== 终端创建用户和数据库

[source,bash]
----
sudo -u postgres createuser --interactive --pwprompt $USER # <1>
sudo -u postgres createdb example_db -O $USER # <2>
----
<1> 创建用户
<2> 创建数据库并指定所有者

当前用户 `$USER` 可直接登陆 PostgreSQL，无需输入密码：

[source,bash]
----
psql -d example_db
\l example_db # <1>
----
<1> 查看数据库基本信息

因为 `/etc/postgresql/16/main/pg_hba.conf` 默认开启了 `peer` 认证，PostgreSQL 通过操作系统获取用户名将其作为数据库用户名直接登陆。

== 常用命令

通过用户 `postgres` 启动客户端:

[source,bash]
----
sudo -u postgres psql
----

`\?`:

[source,psql]
----
\?    -- 帮助
\l    -- 列出所有数据库
\du   -- 列出角色
----

以指定角色（用户）登录指定数据库：

[source,bash]
----
psql -h 127.0.0.1 -U example -d example_db
----

=== 角色

[source,sql]
----
CREATE ROLE example LOGIN PASSWORD 'YOUR_PASSWORD'; -- <1>
ALTER ROLE example PASSWORD 'NEW_PASSWORD'; <2>
DROP ROLE example; -- <3>
----
<1> 创建具备登录权限的角色
<2> 修改密码
<3> 删除角色

=== 数据库

[source,sql]
----
CREATE DATABASE example_db WITH OWNER = example; -- <1>
DROP DATABASE example_db; -- <2>
\c example_db -- <3>
----
<1> 创建数据库并指定所有者
<2> 删除数据库
<3> 连接（使用）数据库

=== 表

[source,sql]
----
CREATE TABLE users (id SERIAL PRIMARY KEY, username VARCHAR(255) NOT NULL); -- <1>
INSERT INTO users (username) values ('notfound');
\dt -- <2>
\d users -- <3>
----
<1> 创建表
<2> 查看当前数据库所有表名
<3> 查看当前数据库 `users` 表信息


== FAQ

* **查看配置文件路径**
+
[source,sql]
----
show config_file;
show hba_file;
----
* **通过 .pgpass 文件免密登录**
+
新建 `~/.pgpass` 文件：
+
.~/.pgpass
[source,text]
----
127.0.0.1:5432:example_db:example:YOUR_PASSWORD
----
+
修改文件权限后登录：
+
[source,bash]
----
chmod 0600 ~/.pgpass
psql -h 127.0.0.1 -U example -d example_db
----
+
* **sql: 错误: 致命错误: 用户 `sample` Ident 认证失败**
+
编辑 `pg_hba.conf`：
+
./etc/postgresql/16/main/pg_hba.conf
[source,conf]
----
# TYPE  DATABASE        USER            ADDRESS                 METHOD
host    all             sample          127.0.0.1/32            md5
----
+
* **修改监听端口，并允许外部客户端连接**
+
编辑 `postgresql.conf`，修改监听端口：
+
./etc/postgresql/16/main/postgresql.conf
[source,conf]
----
listen_addresses = '0.0.0.0'            # what IP address(es) to listen on;
----
+
编辑 `pg_hba.conf`，允许用户 example 在网段 192.168.0.1/16 上访问数据库 example_db：
+
./etc/postgresql/16/main/pg_hba.conf
[source,conf]
----
# TYPE  DATABASE        USER            ADDRESS                 METHOD
host    example_db      example         192.168.0.1/16          md5
----
+
重启服务后，检查端口：
+
[source,bash]
----
sudo systemctl restart postgresql.service
sudo lsof -i:5432
----

== 参考

* https://www.postgresql.org/download/linux/ubuntu
* https://www.postgresql.org/download/linux/redhat/
* https://www.postgresql.org/docs/12/libpq-pgpass.html
* https://www.pgadmin.org/download/pgadmin-4-apt
* https://www.pgadmin.org/download/pgadmin-4-rpm/
