= Spring 授权服务器
notfound <notfound@notfound.cn>
2.0, 2024-01-14: 修改, 1.0, 2021-11-20: 创建
:sectanchors:

:page-slug: spring-oauth2-authorization-server
:page-category: spring
:page-tags: java,spring,oauth

授权服务器主要职责：认证用户身份，管理注册客户端，颁发令牌。

== 获取 OpenID 配置信息

客户端和资源服务器通过如下请求获取 OpenID 配置信息：

[source,js]
----
// GET /.well-known/openid-configuration
{
    "issuer": "http://localhost:9000",
    "authorization_endpoint": "http://localhost:9000/oauth2/authorize",
    "device_authorization_endpoint": "http://localhost:9000/oauth2/device_authorization",
    "token_endpoint": "http://localhost:9000/oauth2/token",
    "token_endpoint_auth_methods_supported": [
        "client_secret_basic",
        "client_secret_post",
        "client_secret_jwt",
        "private_key_jwt"
    ],
    "jwks_uri": "http://localhost:9000/oauth2/jwks",
    "userinfo_endpoint": "http://localhost:9000/userinfo",
    "end_session_endpoint": "http://localhost:9000/connect/logout",
    "response_types_supported": [
        "code"
    ],
    "grant_types_supported": [
        "authorization_code",
        "client_credentials",
        "refresh_token",
        "urn:ietf:params:oauth:grant-type:device_code"
    ],
    "revocation_endpoint": "http://localhost:9000/oauth2/revoke",
    "revocation_endpoint_auth_methods_supported": [
        "client_secret_basic",
        "client_secret_post",
        "client_secret_jwt",
        "private_key_jwt"
    ],
    "introspection_endpoint": "http://localhost:9000/oauth2/introspect",
    "introspection_endpoint_auth_methods_supported": [
        "client_secret_basic",
        "client_secret_post",
        "client_secret_jwt",
        "private_key_jwt"
    ],
    "code_challenge_methods_supported": [
        "S256"
    ],
    "subject_types_supported": [
        "public"
    ],
    "id_token_signing_alg_values_supported": [
        "RS256"
    ],
    "scopes_supported": [
        "openid"
    ]
}
----

== 对象和接口

=== 注册客户端管理

注册客户端对象 RegisteredClient：

[source,java]
----
public class RegisteredClient implements Serializable {
    // 唯一标识
	private String id;
    // 客户端唯一标识，服务器生成
	private String clientId;
	private Instant clientIdIssuedAt;
    // 服务器生成，需要保密，可通过 PasswordEncoder 编码
	private String clientSecret;
	private Instant clientSecretExpiresAt;
	private String clientName;
    // 授权服务器验证客户端的方式，如：client_secret_basic 使用 HTTP Basic 验证方式
	private Set<ClientAuthenticationMethod> clientAuthenticationMethods;
    // 授权类型，如：authorization_code 授权码类型
	private Set<AuthorizationGrantType> authorizationGrantTypes;
    // 授权后重定向 URL
	private Set<String> redirectUris;
	private Set<String> postLogoutRedirectUris;
    // 授权范围
	private Set<String> scopes;
    // 客户端相关配置，如：是否需要验证客户端密钥（require-proof-key)
	private ClientSettings clientSettings;
    // 令牌相关配置，如：授权码（authorization_code ）有效期， 访问令牌（access_token）默认有效期、格式
	private TokenSettings tokenSettings;
    // ...
}
----
* 需要将 RegisteredClient 中的数据持久化到数据库

通过 RegisteredClientRepository 创建、更新、查询 RegisteredClient 对象：

[source,java]
----
public interface RegisteredClientRepository {

	void save(RegisteredClient registeredClient);

	RegisteredClient findById(String id);

	RegisteredClient findByClientId(String clientId);
}
----
* 可使用 JdbcRegisteredClientRepository，或者实现接口并注册为 Bean。

=== 授权、令牌管理

授权对象 OAuth2Authorization：

[source,java]
----
public class OAuth2Authorization implements Serializable {
    // 唯一标识
	private String id;
    // 注册客户端 ID
	private String registeredClientId;
    // 资源所有者名称
	private String principalName;
    // 授权类型，如：authorization_code 授权码
	private AuthorizationGrantType authorizationGrantType;
    // 授权范围
	private Set<String> authorizedScopes;
    // 各种类型令牌，如：授权码 OAuth2AuthorizationCode、访问令牌 OAuth2AccessToken、 刷新令牌 OAuth2RefreshToken
	private Map<Class<? extends OAuth2Token>, Token<?>> tokens;
    // 授权相关的属性
	private Map<String, Object> attributes;
    // ...
}
----
* 需要将 OAuth2Authorization 中的数据持久化到数据库

通过 OAuth2AuthorizationService 创建、更新、删除、查询 OAuth2Authorization 对象：
[source,java]
----
public interface OAuth2AuthorizationService {

	void save(OAuth2Authorization authorization);

	void remove(OAuth2Authorization authorization);

	OAuth2Authorization findById(String id);

	OAuth2Authorization findByToken(String token, @Nullable OAuth2TokenType tokenType);
}
----
* 可使用 JdbcOAuth2AuthorizationService 或者实现接口并注册为 Bean
* 可查询各种类型令牌，如：授权码 OAuth2AuthorizationCode、访问令牌 OAuth2AccessToken、 刷新令牌 OAuth2RefreshToken

== 过程

=== 获取授权码

[source,http]
----
GET /oauth2/authorize
----

获取授权码流程如下：

* `OAuth2AuthorizationEndpointFilter#doFilterInternal`
** `OAuth2AuthorizationCodeRequestAuthenticationConverter#convert` 从请求中提取参数，如 client_id、redirect_uri 等数据创建 Authentication 对象
** `OAuth2AuthorizationCodeRequestAuthenticationProvider#authenticate` 认证，生成授权码
*** `JdbcRegisteredClientRepository#findByClientId` 查询注册客户端
*** `OAuth2AuthenticationValidator#validate` 验证重定向 URL
*** `JdbcOAuth2AuthorizationConsentService#findById`
*** `OAuth2AuthorizationCodeGenerator#generateAuthorizationCode` 生成授权码
*** `JdbcOAuth2AuthorizationService#save` 保存 OAuth2Authorization 对象（持久化）
*** 构建 `OAuth2AuthorizationCodeRequestAuthenticationToken` 对象
** `OAuth2AuthorizationEndpointFilter#sendAuthorizationResponse` 生成带授权码的重定向 URL

与开发者直接相关:

* `JdbcRegisteredClientRepository` 查询注册客户端
* `JdbcOAuth2AuthorizationConsentService`
* `JdbcOAuth2AuthorizationService` 持久化 OAuth2Authorization 对象

**授权码**：随机串进行通过 Base64 编码，需要保存 `authorization_code_value` `authorization_code_issued_at` `authorization_code_expires_at`。

=== 获取访问令牌

[source,http]
----
POST /oauth2/token

{
    "access_token": "*.*.*",
    "refresh_token": "*",
    "scope": "openid",
    "id_token": "*.*.*",
    "token_type": "Bearer",
    "expires_in": 299
}
----

* `OAuth2TokenEndpointFilter#doFilterInternal`
** `OAuth2AuthorizationCodeAuthenticationConverter#convert` 通过请求内容（授权码）创建 Authentication 对象
** `OAuth2AuthorizationCodeAuthenticationProvider#authenticate`
*** `JdbcOAuth2AuthorizationService#findByToken` 通过 token 查询 `OAuth2Authorization`
*** `tokenGenerator` 构建访问令牌、刷新令牌、ID 令牌
**** OAuth2AccessTokenGenerator
**** OAuth2RefreshTokenGenerator
**** JwtGenerator
*** `JdbcOAuth2AuthorizationService#save` 更新 `OAuth2Authorization` 对象（持久化）
*** 返回 `OAuth2AccessTokenAuthenticationToken` 对象
** `OAuth2TokenEndpointFilter#sendAccessTokenResponse` 响应

与开发者直接相关:

- `JdbcOAuth2AuthorizationService` 更新授权对象

**access_token 示例**

JWT 格式 `header.payload.signature`

[source,text]
----
eyJraWQiOiI1Mjk3NTUyZC1mMzlmLTQ3NTgtYTdjNC1kOTNjMTU0NGNmZjMiLCJhbGciOiJSUzI1NiJ9
.
eyJzdWIiOiJ1c2VyIiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTcwNTU4NjQ3OSwic2NvcGUiOlsib3BlbmlkIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcwNTU4Njc3OSwiaWF0IjoxNzA1NTg2NDc5LCJqdGkiOiI0Njg3NGU2ZS1jMjE5LTQxYjUtOTdjZi0zMWFmOWI2NzcxOGUifQ
.
JLtKGTzs4aprbP07DsMsiVUsGVy880N8UzK_It2H5hKDm_DUBsvJmZySJO0-Xq23xWLqNXJW205WkNpsUm4NA26VgV8SAqcG_Xid1NetzUnIQcIo2wHvbsvzbzDwWl-lsYlDyO_-2Fui28jA2u7cs6RJ4tRdYYLogkKeAhQoWC5gTXkJka8jjSKPmHS06wsyBB0_JO8QH6yu-v1ZZmejgFncn1wYqT5aL1XZ_BtD5TnVblaK4j8Bt9rk5eOVu5sBSodnBhaxMy40seyo7J-QOiPPzI_VSGYqldFXxmaPmdjN5JQEsDgkNfNZIcbutFzIuQw4WzkyzIUMY05o8ix6pQ
----

Base64 解码之后：

[source,json]
----
{
    "kid": "5297552d-f39f-4758-a7c4-d93c1544cff3",
    "alg": "RS256"
}
.
{
    "sub": "user",
    "aud": "messaging-client",
    "nbf": 1705586479,
    "scope": ["openid"],
    "iss": "http://localhost:9000",
    "exp": 1705586779,
    "iat": 1705586479,
    "jti": "46874e6e-c219-41b5-97cf-31af9b67718e"
}
.
签名
----
* `kid` key id
* `alg` 签名算法
* `sub(subject)` 令牌的主体。令牌是关于谁的
* `aud(audience)` 令牌的受众。令牌的接受者
* `nbf(not before)` 令牌生效时间
* `iss(issuer)` 令牌的颁发者
* `exp(expiration time)` 令牌过期时间戳
* `iat(issued at)` 令牌颁发时间戳
* `jti(JWT ID)`

**refresh_token**

随机字符串。

**id_token**

JWT 格式 `header.payload.signature`

[source,json]
----
eyJraWQiOiI1Mjk3NTUyZC1mMzlmLTQ3NTgtYTdjNC1kOTNjMTU0NGNmZjMiLCJhbGciOiJSUzI1NiJ9
.
eyJzdWIiOiJ1c2VyIiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsImF6cCI6Im1lc3NhZ2luZy1jbGllbnQiLCJhdXRoX3RpbWUiOjE3MDU1ODYzNjksImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcwNTU4ODI3OSwiaWF0IjoxNzA1NTg2NDc5LCJub25jZSI6IjIzQm1tLTh2NnhubjJRSTJETDlGRWZ4QlFQcGFGbGZNbzhvYlljTXJTeGsiLCJqdGkiOiI4OTdiOTExNi0yNDMzLTQ0MzctOWJhNS1iYTYzZDhmYmJiMmYiLCJzaWQiOiJxNmFmLXp1VC0xd2FLaElPbVhhNkM4dU1ZM083Sm9pcmphMzVBem1tYlpvIn0
.
QTTFt8hcCF9cBDHT1_NdsWNtZJYawAh_46GvsG7CxGvHqOz26Uoz7bna7HAzYQrxddbVSbNHlJanG0Z4CpTgXH3_8FlnByhzVSODb4TqPyNQgK2YUqpX-CarMuHZlcAtkIaQ4YFLMp1SctOKEfp7py9pxPQQBSppcXqFPMUuxZWCTfQfotqe9vqRXG4W97kMPZd6aI7wELAovHvwbRZaLTARpc8ZVUFaLxFuLWmNaSG4Q2uC-byh_OiY6IvtQmqsVq93kvbVD5blNaPSHEynFlKJ-hqrVUYUjIUPakalsNLn03firza39xwYzRmFqvH1TP3JLHySnBUIwi1Cck5Hlw
----

Base64 解码之后：

[source,json]
----
{
    "kid": "5297552d-f39f-4758-a7c4-d93c1544cff3",
    "alg": "RS256"
}
.
{
    "sub": "user",
    "aud": "messaging-client",
    "azp": "messaging-client",
    "auth_time": 1705586369,
    "iss": "http://localhost:9000",
    "exp": 1705588279,
    "iat": 1705586479,
    "nonce": "23Bmm-8v6xnn2QI2DL9FEfxBQPpaFlfMo8obYcMrSxk",
    "jti": "897b9116-2433-4437-9ba5-ba63d8fbbb2f",
    "sid": "q6af-zuT-1waKhIOmXa6C8uMY3O7Joirja35AzmmbZo"
}
.
签名
----
* `kid` key id
* `alg` 签名算法
* `sub(subject)` 令牌的主体。令牌是关于谁的
* `aud(audience)` 令牌的受众。令牌的接受者
* `azp(authorized party)`
* `auth_time` 完成身份认证的时间
* `iss(issuer)` 令牌的颁发者
* `exp(expiration time)` 令牌过期时间戳
* `iat(issued at)` 令牌颁发时间戳
* `nonce` 随机数

=== 获取 JWKs

[source,http]
----
GET /oauth2/jwks
----

* `NimbusJwkSetEndpointFilter`
** `jwkSource` 获取 key 列表
** jwks 响应

与开发者直接相关:

* jwkSource

=== 撤销令牌

[source,http]
----
POST /oauth2/revoke
----
* `OAuth2TokenRevocationEndpointFilter`
** `OAuth2TokenRevocationAuthenticationProvider` 撤销令牌

A Filter for the OAuth 2.0 Token Revocation endpoint.

=== 令牌内省

[source,http]
----
POST /oauth2/introspect
----
* `OAuth2TokenIntrospectionEndpointFilter`
** `OAuth2TokenIntrospectionAuthenticationProvider`

=== 客户端动态注册

[source,http]
----
POST /connect/register
----
* `OidcClientRegistrationEndpointFilter`

=== 请求元数据

[source,http]
----
GET /.well-known/oauth-authorization-server
----

* `OAuth2AuthorizationServerMetadataEndpointFilter`

=== 用户信息

[source,http]
----
GET /userinfo
----

* `OidcUserInfoEndpointFilter`

== 参考

* https://docs.spring.io/spring-authorization-server/reference/getting-started.html
* https://openid.net/specs/openid-connect-discovery-1_0.html
* 《OAuth2 实战》
* https://developers.google.com/identity/openid-connect/openid-connect?hl=zh-cn
