= Ubuntu 安装配置 Spacemacs
notfound <notfound@notfound.cn>
1.0, 2018-12-08: 创建
:sectanchors:

:page-slug: ubuntu-install-spacemacs
:page-category: emacs

== 安装 Emacs 26

Ubuntu 16.04 和 18.04 Emacs 版本都低于 26，可通过 ppa 安装最新的 Emacs 26.x：

[source,bash]
----
sudo add-apt-repository ppa:kelleyk/emacs
sudo apt-get update
sudo apt-get install emacs26
----

== 安装 Spacemacs

https://github.com/syl20bnr/spacemacs[spacemacs] master 更新太慢，使用 develop 分支。

[source,bash]
----
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
----

启动 emacs，首次启动会有两个选项，直接回车选择默认值即可，之后会下载依赖，并自动生成配置文件 `~/.spacemacs` 。

创建目录 `.spacemacs.d` 用来存放自定义配置，可使用 git 等工具进行同步和版本控制。 https://github.com/syl20bnr/spacemacs/blob/develop/doc/QUICK%5FSTART.org#dotdirectory-spacemacsd[文件加载顺序说明]

[source,bash]
----
mkdir ~/.spacemacs.d
mv ~/.spacemacs ~/.spacemacs.d/init.el
----

== 配置

可通过 `SPC f e d` 快速打开配置文件。

=== 图标

编辑 `/usr/share/applications/emacs26.desktop` https://askubuntu.com/questions/726351/use-desktop-icon-for-running-application[参考] ：

[source,bash]
----
StartupWMClass=Emacs26
Icon=/home/notfound/.emacs.d/core/banners/img/spacemacs.png
----

=== 源

国外源下载速度慢，添加 https://mirrors.cloud.tencent.com/help/elpa.html[国内的源] 。在 `dotspacemacs/user-init` 中添加：

[source,lisp]
----
(setq configuration-layer-elpa-archives
      '(("melpa-cn" . "http://mirrors.cloud.tencent.com/elpa/melpa/")
        ("org-cn"   . "http://mirrors.cloud.tencent.com/elpa/org/")
        ("gnu-cn"   . "http://mirrors.cloud.tencent.com/elpa/gnu/")))
----

=== 复制粘贴

emacs 会拦截鼠标事件，点击鼠标右键没菜单， `Ctrl+c` 也无法使用。

layer `xclipboard` 可以通过 `SPC x p` 粘贴， `SPC x y` 复制。 https://github.com/syl20bnr/spacemacs/tree/develop/layers/+tools/xclipboard[参考]

在终端模式复制粘贴，在 `dotspacemacs/user-config` 中添加：

[source,lisp]
----
(xterm-mouse-mode -1)
----

终端中，可通过 `Ctrl Shift c` 复制， `Ctrl Shift v` 粘贴，但在复制时行末尾的空白会变成多余的空格。 https://www.reddit.com/r/spacemacs/comments/7ax52t/how%5Fto%5Fcopypaste%5Ffrom%5Fthe%5Fhost%5Fclipboard%5Fin[参考]

=== 搜索

传说 `ag` 比 `grep` 快，所以安装 `ag` 。

[source,bash]
----
sudo apt install silversearcher-ag
----

默认搜索工具使用顺序为 `rg` > `ag` > `pt` > `ack` > `grep` ，所以安装 `ag` 后就不会使用 `grep` 。

==== 文件过滤

搜索时可能需要过滤掉某些文件，默认情况下会使用 `.gitignore` 和 `.hgignore` 。

可在项目或者 home 目录下添加文件 `.agignore` （或 `.ignore` 2.0.0+ ）。 https://github.com/ggreer/the%5Fsilver%5Fsearcher/wiki/Advanced-Usage[参考]

==== 按键

* `SPC *` 或 `SPC s P` 搜索当前光标位置的值
* `SPC /` 或 `SPC s p` 搜索
* `SPC s a p` 使用 `ag` 搜索当前项目下的文件
* `SPC r s` 唤醒上次搜索 buffer

=== 跳转

添加 https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Btags/gtags[gtags] layer。

==== 安装

[source,bash]
----
sudo apt install global
sudo apt install exuberant-ctags python-pygments
----

==== 配置

使用 ctags 生成标签，可添加环境变量：

[source,bash]
----
export GTAGSLABEL=ctags
----

如果需要自定义忽略的文件和目录，可通过 `~/.globalrc` 进行配置（文件内搜索 `skip` ）:

* Ubuntu 16.04: `vim /usr/share/doc/global/examples/gtags.conf.gz` 然后 `:w ~/.globalrc`
* Ubuntu 18.04: `cp /usr/share/doc/global/examples/gtags.conf ~/.globalrc`
* `gtags.conf` 跨版本的配置可能不兼容，会出现错误

==== 按键

* `SPC p g` 或 `SPC m g C` 生成 tag
* `SPC p g` 查找 tag

tags 信息保存在 `GPATH` 、 `GRTAGS` 、 `GTAGS` 三个文件中，需要在版本控制中忽略这三个文件。

=== 其他常用 layers

* https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bsource-control/git[git] 使用了 https://magit.vc/[magit]
* https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bsource-control/version-control[version-control] 可用来显示文件变更
* https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Btools/restclient[restclient] 可用来发送 http 请求
* https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bcompletion/auto-completion[auto-completion] 自动补全
* https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bemacs/org[org] org-mode 功能强大
* https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/asciidoc[asciidoc]
* https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/markdown[markdown]
* https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/yaml[yaml]
* https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/sql[sql]
* https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/html[html]
* https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/javascript[javascript]
* https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/json[json]
* https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/ruby[ruby]
* https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bframeworks/ruby-on-rails[ruby-on-rails]

=== 其他

* https://github.com/bbatsov/projectile[projectile] 项目管理
